/**
 * MainWindow.cpp - Moil's XUnity LLM Translator GUI Implementation
 * MainWindow.cpp - Moil的XUnity大模型翻译器GUI实现
 * Updated by CAN: Merged detailed tooltips with full functionality.
 * 由CAN更新：合并详细工具提示与完整功能
 */

#include "MainWindow.h"
#include "json.hpp"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QGroupBox>
#include <QFileDialog>
#include <QMessageBox>
#include <QApplication>
#include <QFile>
#include <QTextStream>
#include <QCloseEvent>
#include <QStyleFactory>
#include <QPixmap>
#include <QMenu>
#include <QScrollBar>
#include <QGraphicsOpacityEffect>
#include <QPropertyAnimation>
#include <QListView> 
#include <QDesktopServices>
#include <QUrl>
#include <QFileInfo>

// ==========================================
// 🌍 多语言字典定义 (UI Text)
// 🌍 Multi-language Dictionary Definition (UI Text)
// Index 0: English, Index 1: Chinese
// 索引0: 英文, 索引1: 中文
// ==========================================

// 窗口标题 / Window titles
const char* STR_TITLE[] = {"Moil's XUnity LLM Translator", "Moil的XUnity大模型翻译GUI"};

// 配置区域标题 / Configuration section titles
const char* STR_API_CFG[] = {"API Configuration", "API 配置"};
const char* STR_LOG_AREA[] = {"Runtime Logs", "运行日志"};

// API配置相关文本 / API configuration related text
const char* STR_API_ADDR[] = {"API Address:", "API 地址:"};
const char* STR_API_KEY[] = {"API Key:", "API 密钥:"};
const char* STR_MODEL[] = {"Model Name:", "模型名称:"};
const char* STR_FETCH[] = {"Fetch", "获取"};

// 服务器参数文本 / Server parameter text
const char* STR_PORT[] = {"Port:", "端口:"};
const char* STR_THREAD[] = {"Threads:", "线程:"};
const char* STR_TEMP[] = {"Temp:", "温度:"};
const char* STR_CTX[] = {"Context:", "上下文:"};

// 提示词相关文本 / Prompt related text
const char* STR_SYS_PROMPT[] = {"System Prompt:", "系统提示:"};
const char* STR_PRE_PROMPT[] = {"Pre-Prompt:", "前置文本:"};

// 控制按钮文本 / Control button text
const char* STR_START[] = {"Start Service", "启动服务"};
const char* STR_STOP[] = {"Stop Service", "停止服务"};
const char* STR_HUD[] = {"HUD Mode", "HUD 模式"};
const char* STR_TEST[] = {"Test Config", "测试配置"};
const char* STR_LOAD[] = {"Load Config", "读取配置"};
const char* STR_SAVE[] = {"Save Config", "保存配置"};
const char* STR_EXPORT[] = {"Export Log", "导出日志"};

// 主题和语言文本 / Theme and language text
const char* STR_THEME_LIGHT[] = {"Light Mode", "切换亮色"};
const char* STR_THEME_DARK[] = {"Dark Mode", "切换暗色"};
const char* STR_LANG_BTN[] = {"中文", "English"}; // 按钮文本通常显示目标语言 / Button text usually shows target language

// 术语表相关文本 / Glossary related text
const char* STR_GLOSSARY[] = {"Glossary:", "术语表:"};
const char* STR_CHK_GLOSSARY[] = {"Self-Evolve", "启用自进化"};
const char* STR_CLEAR_LOG[] = {"Clear Log", "清空日志"};

// Token统计文本 / Token statistics text
const char* STR_TOKENS[] = {"Tokens:", "消耗:"};
const char* TIP_TOKENS[] = {"Total Usage (Prompt + Completion)", "本次运行总消耗 (输入+输出)"};

// ==========================================
// 📝 多语言字典定义 (Logs)
// 📝 Multi-language Dictionary Definition (Logs)
// Index 0: English, Index 1: Chinese
// 索引0: 英文, 索引1: 中文
// ==========================================

// 日志消息 / Log messages
const char* LOG_TEST_START[] = {"=== Testing API Keys ===", "=== 开始测试所有 API Key ==="};
const char* LOG_NO_KEY[] = {"❌ No API Key", "❌ 未找到 API Key"};
const char* LOG_PASS[] = {"Pass", "测试通过"};
const char* LOG_FAIL[] = {"Fail", "失败"};
const char* LOG_FETCH_SUCCESS[] = {"Fetch Models Success", "模型列表获取成功"};
const char* LOG_FETCH_FAIL[] = {"Fetch Failed: ", "获取失败: "};
const char* LOG_PARSE_ERR[] = {"Parse Error", "解析错误"};
const char* LOG_CFG_SAVED[] = {"Config Saved: ", "配置已保存: "};
const char* LOG_CFG_LOADED[] = {"Config Loaded: ", "配置已加载: "};
const char* LOG_EXPORTED[] = {"Log Exported to run_log.txt", "日志已导出到 run_log.txt"};

// 上下文清理相关文本 / Context clearing related text
const char* STR_CLEAR_CTX[] = {"Clear", "清空"};
const char* TIP_CLEAR_CTX[] = {"Clear Context", "清除历史对话记忆"};

// 📝 新增按钮文本 / New button text
const char* STR_BTN_AUTO[] = {"Edit", "编辑"};
const char* TIP_BTN_AUTO[] = {
    "Open _AutoGeneratedTranslations.txt in same folder", 
    "打开同目录下的 _AutoGeneratedTranslations.txt (自动翻译结果)"
};

// ==========================================
// 💡 详细工具提示 (Detailed Tooltips) - Merged
// 💡 Detailed Tooltips (Detailed Tooltips) - Merged
// Index 0: English, Index 1: Chinese
// 索引0: 英文, 索引1: 中文
// ==========================================

// 端口提示 / Port tooltip
const char* TIP_PORT[] = {
    "Local Listening Port\nEnsure XUnity Endpoint is set to http://localhost:port",
    "本地监听端口\n请确保 XUnity 配置文件 Endpoint 设置为 http://localhost:端口号"
};

// 线程提示 / Thread tooltip
const char* TIP_THREAD[] = {
    "Concurrent Threads\nRecommended: Depends on your CPU\nNote: Can speed up translation to some extent, too many may cause system lag",
    "并发线程数 (Max Threads)\n建议值: 取决于你电脑的线程数\n注意: 一定程度上可以加快翻译工作，过多会导致系统卡顿"
};

// 温度提示 / Temperature tooltip
const char* TIP_TEMP[] = {
    "Sampling Temperature\n0.0-0.3: Strict\n0.7-1.0: Standard\n>1.0: Creative/Random",
    "采样温度 (Temperature)\n0.0-0.3: 严谨\n0.7-1.0: 标准\n>1.0: 随机/创造性"
};

// 上下文提示 / Context tooltip
const char* TIP_CTX[] = {
    "Context Memory\nNumber of history turns to carry.\nNote: More context consumes more tokens.",
    "上下文记忆 (Context)\n携带的历史对话轮数。\n注意：上下文越多，消耗 Token 越多。"
};

// 术语表提示 / Glossary tooltip
const char* TIP_GLOSSARY[] = {
    "Select XUnity's _Substitutions.txt.\nLLM will reference and append to it.",
    "选择 XUnity 的 _Substitutions.txt 文件。\nLLM 将自动参考并补充该文件。"
};

// API下拉框提示 / API combobox tip
const char* TIP_COMBO_MAIN[] = {
    "Enter API Address or select from list.\nMust support /v1/chat/completions format.",
    "在此输入 API 地址，或从下拉列表中选择主流服务商。\n所有地址必须兼容 OpenAI 接口格式 (/v1/chat/completions)。"
};

// ==========================================
// ⚙️ API Presets
// ⚙️ API预设
// ==========================================

// API预设数据结构 / API preset data structure
struct ApiPresetDef {
    const char* url;          // API地址 / API URL
    const char* tips[2];      // 提示信息数组 [0:英文, 1:中文] / Tip array [0:English, 1:Chinese]
};

// API预设数据 / API preset data
const ApiPresetDef PRESETS_DATA[] = {
    {"https://api.openai.com/v1", {"OpenAI Official API", "OpenAI 官方接口"}},
    {"https://api.deepseek.com", {"DeepSeek Official API", "DeepSeek 官方接口"}},
    {"https://api.x.ai/v1", {"Grok (xAI) Official API", "Grok (xAI) 官方接口"}},
    {"https://api.siliconflow.cn/v1", {"SiliconFlow", "硅基流动 (SiliconFlow)"}},
    {"https://openrouter.ai/api/v1", {"OpenRouter Aggregator", "OpenRouter 聚合平台"}},
    {"https://generativelanguage.googleapis.com/v1beta/openai", {"Google Gemini", "Google Gemini (OpenAI 兼容端点)"}},
    {"http://localhost:11434/v1", {"Ollama Local Service", "Ollama 本地服务"}},
    {"http://localhost:1234/v1", {"LM Studio Local Service", "LM Studio 本地服务"}}
};

// ==========================================
// 🚀 Implementation
// 🚀 实现
// ==========================================

/**
 * MainWindow类构造函数
 * MainWindow class constructor
 * @param parent 父窗口指针 / Parent widget pointer
 */
MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent) {
    // 初始化成员变量 / Initialize member variables
    m_isClosing = false;
    m_isDarkTheme = true;
    m_currentLang = 1; // 默认中文 / Default to Chinese

    // 设置窗口大小 / Set window size
    resize(400, 800);

    // 创建Token管理器和翻译服务器 / Create TokenManager and TranslationServer
    m_tokenManager = new TokenManager(this);
    server = new TranslationServer(this);
    
    // 创建HUD窗口 / Create HUD window
    m_hudWindow = new HudWindow(nullptr);
    
    // 设置UI / Setup UI
    setupUi();

    // 连接信号和槽 / Connect signals and slots
    connect(server, &TranslationServer::logMessage, this, &MainWindow::onLogMessage);
    connect(server, &TranslationServer::tokenUsageReceived, m_tokenManager, &TokenManager::addUsage);
    connect(m_tokenManager, &TokenManager::tokensUpdated, this, &MainWindow::updateTokenDisplay);

    // HUD窗口相关连接 / HUD window related connections
    connect(m_hudWindow, &HudWindow::requestRestore, this, &MainWindow::restoreFromHud);
    connect(m_tokenManager, &TokenManager::tokensUpdated,  [this](long long t, long long, long long){
        if(m_hudWindow) m_hudWindow->updateTokens(t);
    });
    
    // 服务器工作状态连接 / Server work status connections
    connect(server, &TranslationServer::workStarted, this, &MainWindow::onServerWorkStarted);
    connect(server, &TranslationServer::workFinished, this, &MainWindow::onServerWorkFinished);

    // 加载配置并更新UI文本 / Load config and update UI text
    loadConfigToUi();
    updateUIText();
    
    // 应用暗色主题 / Apply dark theme
    applyTheme(true); 

    // 设置窗口淡入动画 / Set window fade-in animation
    setWindowOpacity(0.0);
    fadeAnim = new QPropertyAnimation(this, "windowOpacity");
    fadeAnim->setDuration(500);
    fadeAnim->setStartValue(0.0);
    fadeAnim->setEndValue(1.0);
    fadeAnim->start();
}

/**
 * MainWindow类析构函数
 * MainWindow class destructor
 */
MainWindow::~MainWindow() {
    // 关闭并删除HUD窗口 / Close and delete HUD window
    if (m_hudWindow) {
        m_hudWindow->close();
        delete m_hudWindow;
    }
    
    // 停止服务器 / Stop server
    server->stopServer();
}

/**
 * 窗口关闭事件处理
 * Window close event handler
 * @param event 关闭事件对象 / Close event object
 */
void MainWindow::closeEvent(QCloseEvent *event) {
    // 如果正在关闭中，直接接受事件 / If already closing, accept event directly
    if (m_isClosing) {
        event->accept();
        return;
    }
    
    // 保存配置到文件 / Save config to file
    ConfigManager::saveConfig(getUiConfig(), "config.ini");
    
    // 如果HUD窗口可见，关闭它 / If HUD window is visible, close it
    if (m_hudWindow->isVisible()) {
        m_hudWindow->close();
    }
    
    // 忽略事件，开始淡出动画 / Ignore event, start fade out animation
    event->ignore();
    m_isClosing = true;
    fadeOutAndClose();
}

/**
 * 淡出并关闭窗口
 * Fade out and close window
 */
void MainWindow::fadeOutAndClose() {
    // 设置动画反向播放 / Set animation to play backwards
    fadeAnim->setDirection(QAbstractAnimation::Backward);
    
    // 动画完成时关闭窗口和应用程序 / Close window and application when animation finishes
    connect(fadeAnim, &QPropertyAnimation::finished, this, &QMainWindow::close);
    connect(fadeAnim, &QPropertyAnimation::finished, qApp, &QApplication::quit);
    
    fadeAnim->start();
}

/**
 * 平滑切换效果
 * Smooth switching effect
 * @param changeLogic 需要执行的切换逻辑 / Switching logic to execute
 */
void MainWindow::smoothSwitch(std::function<void()> changeLogic) {
    // 捕获当前窗口截图 / Capture current window screenshot
    QPixmap pixmap = this->grab();
    QLabel* overlay = new QLabel(this);
    overlay->setPixmap(pixmap);
    overlay->setGeometry(0, 0, this->width(), this->height());
    overlay->show();

    // 执行切换逻辑 / Execute switching logic
    changeLogic();

    // 创建淡出效果 / Create fade out effect
    QGraphicsOpacityEffect* effect = new QGraphicsOpacityEffect(overlay);
    overlay->setGraphicsEffect(effect);

    // 创建动画 / Create animation
    QPropertyAnimation* anim = new QPropertyAnimation(effect, "opacity");
    anim->setDuration(300);
    anim->setStartValue(1.0);
    anim->setEndValue(0.0);
    
    // 动画完成时删除覆盖层 / Delete overlay when animation finishes
    connect(anim, &QPropertyAnimation::finished, overlay, &QLabel::deleteLater);
    anim->start(QAbstractAnimation::DeleteWhenStopped);
}

/**
 * 切换语言
 * Toggle language
 */
void MainWindow::toggleLanguage() {
    smoothSwitch([this](){
        // 切换语言索引 / Toggle language index
        m_currentLang = (m_currentLang == 0) ? 1 : 0;
        
        // 更新UI文本 / Update UI text
        updateUIText();
        
        // 更新主题按钮文本 / Update theme button text
        if(themeBtn) themeBtn->setText(m_isDarkTheme ? STR_THEME_LIGHT[m_currentLang] : STR_THEME_DARK[m_currentLang]);
        
        // 更新服务器配置 / Update server configuration
        server->updateConfig(getUiConfig());
        
        // 处理事件并调整窗口大小 / Process events and adjust window size
        qApp->processEvents();
        adjustSize();
        resize(400, 800); 
    });
}

/**
 * 切换主题
 * Toggle theme
 */
void MainWindow::toggleTheme() {
    smoothSwitch([this](){
        // 应用相反的主题 / Apply opposite theme
        applyTheme(!m_isDarkTheme);
    });
}

/**
 * 添加术语表文件到历史记录
 * Add glossary file to history
 * @param path 术语表文件路径 / Glossary file path
 */
void MainWindow::addToGlossaryHistory(const QString& path) {
    if (path.isEmpty()) return;
    
    // 获取当前历史记录 / Get current history
    QStringList items;
    for (int i = 0; i < glossaryCombo->count(); ++i) {
        items << glossaryCombo->itemText(i);
    }
    
    // 移除重复项并添加到首位 / Remove duplicates and add to front
    items.removeAll(path);
    items.insert(0, path);
    
    // 限制历史记录数量 / Limit history count
    while (items.size() > 5) {
        items.removeLast();
    }
    
    // 更新下拉框 / Update combobox
    glossaryCombo->clear();
    glossaryCombo->addItems(items);
    glossaryCombo->setCurrentIndex(0); 
}

/**
 * 选择术语表文件
 * Select glossary file
 */
void MainWindow::onSelectGlossary() {
    // 打开文件对话框 / Open file dialog
    QString fileName = QFileDialog::getOpenFileName(this, "Select File", "", "Text Files (*.txt);;All Files (*.*)");
    
    // 如果选择了文件，添加到历史记录 / If file selected, add to history
    if (!fileName.isEmpty()) {
        addToGlossaryHistory(fileName);
    }
}

/**
 * 打开自动翻译文件
 * Open auto-generated translations file
 */
void MainWindow::onOpenAutoTranslations() {
    // 获取当前术语表路径 / Get current glossary path
    QString currentPath = glossaryCombo->currentText();
    if (currentPath.isEmpty()) {
        return;
    }

    // 获取目录并构建自动翻译文件路径 / Get directory and build auto translation file path
    QFileInfo fi(currentPath);
    QString dir = fi.absolutePath();
    
    // 假设自动生成文件与 _Substitutions.txt 在同一目录
    // Assuming auto-generated file is in same directory as _Substitutions.txt
    QString targetFile = dir + "/_AutoGeneratedTranslations.txt";

    // 检查文件是否存在 / Check if file exists
    QFileInfo targetFi(targetFile);
    if (!targetFi.exists()) {
        QMessageBox::warning(this, 
            (m_currentLang == 1 ? "文件未找到" : "File Not Found"), 
            (m_currentLang == 1 ? "未找到 _AutoGeneratedTranslations.txt。\n请确认游戏是否已经运行并生成了翻译。" : 
            "Could not find _AutoGeneratedTranslations.txt.\nPlease ensure the game has run and generated translations."));
        return;
    }

    // 使用系统默认编辑器打开 / Open with system default editor
    QDesktopServices::openUrl(QUrl::fromLocalFile(targetFile));
}

/**
 * 更新UI文本（多语言支持）
 * Update UI text (multi-language support)
 */
void MainWindow::updateUIText() {
    // 根据当前语言获取索引 / Get index based on current language
    int i = m_currentLang;
    
    // 设置窗口标题 / Set window title
    setWindowTitle(STR_TITLE[i]);
    
    // 设置组框标题 / Set group box titles
    cfgGroup->setTitle(STR_API_CFG[i]);
    logGroup->setTitle(STR_LOG_AREA[i]);

    // 设置API配置标签 / Set API configuration labels
    lblApiAddr->setText(STR_API_ADDR[i]);
    lblApiKey->setText(STR_API_KEY[i]);
    lblModel->setText(STR_MODEL[i]);
    fetchModelBtn->setText(STR_FETCH[i]);

    // 设置服务器参数标签 / Set server parameter labels
    lblPort->setText(STR_PORT[i]);
    lblThread->setText(STR_THREAD[i]);
    lblTemp->setText(STR_TEMP[i]);
    lblCtx->setText(STR_CTX[i]);
    
    // 设置提示词标签 / Set prompt labels
    lblSysPrompt->setText(STR_SYS_PROMPT[i]);
    lblPrePrompt->setText(STR_PRE_PROMPT[i]);

    // 设置上下文清理按钮 / Set context clear button
    clearCtxBtn->setText(STR_CLEAR_CTX[i]);
    clearCtxBtn->setToolTip(TIP_CLEAR_CTX[i]);

    // 设置术语表相关控件 / Set glossary related controls
    lblGlossary->setText(STR_GLOSSARY[i]);
    chkGlossary->setText(STR_CHK_GLOSSARY[i]);

    // 设置控制按钮文本 / Set control button text
    startBtn->setText(STR_START[i]);
    stopBtn->setText(STR_STOP[i]);
    hudBtn->setText(STR_HUD[i]); 
    testBtn->setText(STR_TEST[i]);
    loadBtn->setText(STR_LOAD[i]);
    saveBtn->setText(STR_SAVE[i]);
    exportBtn->setText(STR_EXPORT[i]);
    langBtn->setText(STR_LANG_BTN[i]);

    // 设置自动翻译按钮 / Set auto translation button
    if (btnOpenAuto) {
        btnOpenAuto->setText(STR_BTN_AUTO[i]);
        btnOpenAuto->setToolTip(TIP_BTN_AUTO[i]);
    }

    // 🌟 更新为详细的 Tooltips 🌟
    // 🌟 Update to detailed tooltips 🌟
    portEdit->setToolTip(TIP_PORT[i]);
    lblPort->setToolTip(TIP_PORT[i]);
    
    threadSpin->setToolTip(TIP_THREAD[i]);
    lblThread->setToolTip(TIP_THREAD[i]);
    
    tempSpin->setToolTip(TIP_TEMP[i]);
    lblTemp->setToolTip(TIP_TEMP[i]);
    
    contextSpin->setToolTip(TIP_CTX[i]);
    lblCtx->setToolTip(TIP_CTX[i]);

    // 设置术语表工具提示 / Set glossary tooltips
    lblGlossary->setToolTip(TIP_GLOSSARY[i]);
    chkGlossary->setToolTip(TIP_GLOSSARY[i]);
    btnSelectGlossary->setToolTip(TIP_GLOSSARY[i]);
    
    if (glossaryCombo) {
        glossaryCombo->setToolTip(TIP_GLOSSARY[i]);
    }
    
    // 设置HUD按钮工具提示 / Set HUD button tooltip
    hudBtn->setToolTip(i==0 ? "Switch to Mini-HUD mode" : "切换至迷你悬浮窗模式");
    
    // 更新API下拉框提示和选项提示 / Update API combobox tooltip and item tooltips
    if (apiAddressCombo) {
        apiAddressCombo->setToolTip(TIP_COMBO_MAIN[i]);
        
        // 遍历更新下拉选项的提示 / Iterate to update dropdown item tooltips
        for (int k = 0; k < apiAddressCombo->count(); ++k) {
            QString itemUrl = apiAddressCombo->itemText(k);
            
            // 在预设列表中查找对应的URL / Find corresponding URL in preset list
            for (const auto& preset : PRESETS_DATA) {
                if (itemUrl == preset.url) {
                    // 设置对应语言的提示 / Set tooltip in corresponding language
                    apiAddressCombo->setItemData(k, preset.tips[i], Qt::ToolTipRole);
                    break;
                }
            }
        }
    }

    // 更新Token显示 / Update token display
    lblTokens->setText(QString("%1 %2").arg(STR_TOKENS[i]).arg(m_tokenManager->getTotal()));
    lblTokens->setToolTip(TIP_TOKENS[i]);
}

/**
 * 应用主题样式
 * Apply theme styling
 * @param isDark 是否为暗色主题 / Whether to apply dark theme
 */
void MainWindow::applyTheme(bool isDark) {
    // 恢复默认样式 / Restore default style
    qApp->setStyle(QStyleFactory::create("Fusion"));
    
    // 定义颜色变量 / Define color variables
    QColor windowColor, baseColor, textColor, btnColor, highlightColor, linkColor;
    QString qssBtnBorder, qssBtnBg, qssBtnHover;
    
    // 下拉按钮专用的反差色 / Contrast colors specifically for dropdown buttons
    QString dropDownBg, dropDownHover; 
    
    // 设置深色或亮色模式的配色方案
    // Set color scheme for dark or light mode
    if (isDark) {
        // === 深色模式配色 / Dark mode color scheme ===
        windowColor = QColor(30, 30, 30);    
        baseColor   = QColor(37, 37, 38);    // 输入框背景 / Input field background: Dark gray
        textColor   = QColor(220, 220, 220); 
        btnColor    = QColor(60, 60, 60);    
        highlightColor = QColor(0, 122, 204); 
        linkColor   = QColor(86, 156, 214);
        qssBtnBorder = "#555555";
        qssBtnBg     = "#3C3C3C";
        qssBtnHover  = "#505050";
        
        // 反差色设计：背景黑 -> 按钮亮 / Contrast design: Black background -> Light buttons
        dropDownBg    = "#C0C0C0"; 
        dropDownHover = "#FFFFFF"; 
        
        // 更新主题按钮文本 / Update theme button text
        if(themeBtn) themeBtn->setText(STR_THEME_LIGHT[m_currentLang]);
    } else {
        // === 亮色模式配色 / Light mode color scheme ===
        windowColor = QColor(240, 240, 240);
        baseColor   = QColor(255, 255, 255); // 输入框背景 / Input field background: Pure white
        textColor   = QColor(0, 0, 0);
        btnColor    = QColor(225, 225, 225);
        highlightColor = QColor(0, 120, 215);
        linkColor   = QColor(0, 0, 255);
        qssBtnBorder = "#C0C0C0";
        qssBtnBg     = "#E1E1E1";
        qssBtnHover  = "#D0D0D0";
        
        // 反差色设计：背景白 -> 按钮暗 / Contrast design: White background -> Dark buttons
        dropDownBg    = "#4D4D4D"; 
        dropDownHover = "#2D2D2D"; 
        
        // 更新主题按钮文本 / Update theme button text
        if(themeBtn) themeBtn->setText(STR_THEME_DARK[m_currentLang]);
    }
    
    // 设置全局调色板 / Set global palette
    QPalette p;
    p.setColor(QPalette::Window, windowColor);
    p.setColor(QPalette::WindowText, textColor);
    p.setColor(QPalette::Base, baseColor); 
    p.setColor(QPalette::AlternateBase, windowColor);
    p.setColor(QPalette::ToolTipBase, baseColor);
    p.setColor(QPalette::ToolTipText, textColor);
    p.setColor(QPalette::Text, textColor);
    p.setColor(QPalette::Button, btnColor);
    p.setColor(QPalette::ButtonText, textColor);
    p.setColor(QPalette::Link, linkColor);
    p.setColor(QPalette::Highlight, highlightColor);
    p.setColor(QPalette::HighlightedText, Qt::white);
    qApp->setPalette(p);
    
    // 应用QSS样式表 / Apply QSS stylesheet
    // CAN UPDATED: Changed QToolTip color from %6 (highlightColor) to #E6B422 (Gold)
    QString qss = QString(R"(
        QGroupBox { border: 1px solid %1; border-radius: 5px; margin-top: 1.2em; font-weight: bold; }
        QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; left: 10px; padding: 0 3px; color: %6; }
        QPushButton { border: 1px solid %3; border-radius: 4px; background-color: %4; padding: 5px; font-weight: bold; }
        QPushButton:hover { background-color: %5; border-color: %2; }
        QPushButton:pressed { background-color: %2; color: white; border-color: %2; }
        QPushButton:disabled { background-color: transparent; border: 1px solid %1; color: gray; }
        
        QLineEdit, QComboBox { border: 1px solid %3; border-radius: 4px; background-color: %7; padding: 4px; color: palette(text); selection-background-color: %2; }
        QComboBox:hover, QLineEdit:hover { border-color: %2; }
        
        QComboBox::drop-down { subcontrol-origin: padding; subcontrol-position: top right; width: 25px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; background-color: %9; border-left-width: 1px; border-left-color: %3; border-left-style: solid; }
        QComboBox::drop-down:hover { background-color: %10; }
        QComboBox::down-arrow { image: none; width: 0px; height: 0px; border: none; }
        QComboBox QAbstractItemView { border: 1px solid %2; selection-background-color: %2; background-color: %7; outline: none; }
        
        QPushButton#btnStart { background-color: #388E3C; color: white; border: 1px solid #2E7D32; }
        QPushButton#btnStart:hover { background-color: #4CAF50; border-color: #43A047; }
        QPushButton#btnStart:pressed { background-color: #1B5E20; border-color: #1B5E20; }
        QPushButton#btnStart:disabled { background-color: transparent; border: 1px solid %1; color: gray; }
        QLabel#lblTokens { color: #E6B422; font-weight: bold; }
        
        QToolTip { border: 1px solid %2; background-color: %7; color: #E6B422; opacity: 230; padding: 4px; border-radius: 3px; }
    )")
    .arg(qssBtnBorder).arg(highlightColor.name()).arg(qssBtnBorder).arg(qssBtnBg).arg(qssBtnHover)
    .arg(highlightColor.name()).arg(baseColor.name()).arg(textColor.name()).arg(dropDownBg).arg(dropDownHover);
    
    qApp->setStyleSheet(qss);
    
    // 更新主题状态 / Update theme state
    m_isDarkTheme = isDark;
}

/**
 * 设置UI界面
 * Setup UI interface
 */
void MainWindow::setupUi() {
    // 创建中心部件和主布局 / Create central widget and main layout
    QWidget *central = new QWidget(this);
    setCentralWidget(central);
    QVBoxLayout *mainLayout = new QVBoxLayout(central);
    mainLayout->setSpacing(10);
    mainLayout->setContentsMargins(10, 10, 10, 10);

    // === 配置组框 / Configuration GroupBox ===
    cfgGroup = new QGroupBox(this);
    QGridLayout *grid = new QGridLayout(cfgGroup);
    grid->setColumnStretch(1, 1);
    grid->setVerticalSpacing(8);
    grid->setHorizontalSpacing(10);

    // 标签创建辅助函数 / Label creation helper function
    auto createLabel = [this](QLabel*& memberPtr) {
        memberPtr = new QLabel(this);
        memberPtr->setAlignment(Qt::AlignRight | Qt::AlignVCenter);
        return memberPtr;
    };

    // API地址下拉框 / API address combobox
    apiAddressCombo = new QComboBox(this);
    apiAddressCombo->setEditable(true); 
    apiAddressCombo->setMinimumHeight(28);
    
    // 从全局字典加载预设 / Load presets from global dictionary
    for(const auto& p : PRESETS_DATA) {
        apiAddressCombo->addItem(p.url);
        // 初始加载时，根据当前语言设置提示 / Set tooltip based on current language during initial load
        apiAddressCombo->setItemData(apiAddressCombo->count()-1, p.tips[m_currentLang], Qt::ToolTipRole);
    }
    apiAddressCombo->setCurrentIndex(0);

    grid->addWidget(createLabel(lblApiAddr), 0, 0);
    grid->addWidget(apiAddressCombo, 0, 1);

    // API密钥输入框 / API key input field
    apiKeyEdit = new QLineEdit(this);
    apiKeyEdit->setEchoMode(QLineEdit::Normal); 
    grid->addWidget(createLabel(lblApiKey), 1, 0);
    grid->addWidget(apiKeyEdit, 1, 1);

    // 模型获取行 / Model fetch row
    QWidget *modelContainer = new QWidget(this);
    QHBoxLayout *modelLayout = new QHBoxLayout(modelContainer);
    modelLayout->setContentsMargins(0, 0, 0, 0);
    modelLayout->setSpacing(5);
    
    modelCombo = new QComboBox(this);
    modelCombo->setEditable(true);
    modelCombo->setMinimumHeight(28); 
    
    fetchModelBtn = new QPushButton(this);
    connect(fetchModelBtn, &QPushButton::clicked, this, &MainWindow::onFetchModels);
    
    modelLayout->addWidget(modelCombo, 1); 
    modelLayout->addWidget(fetchModelBtn);
    grid->addWidget(createLabel(lblModel), 2, 0);
    grid->addWidget(modelContainer, 2, 1);

    // 参数行 / Parameters row
    QWidget *paramContainer = new QWidget(this);
    QHBoxLayout *paramLayout = new QHBoxLayout(paramContainer);
    paramLayout->setContentsMargins(0, 0, 0, 0);
    paramLayout->setSpacing(8); 

    // 创建参数控件 / Create parameter controls
    lblPort = new QLabel(this);
    portEdit = new QLineEdit(this);
    portEdit->setFixedWidth(55);
    portEdit->setAlignment(Qt::AlignCenter);

    lblThread = new QLabel(this);
    threadSpin = new QSpinBox(this);
    threadSpin->setRange(1, 200);
    threadSpin->setFixedWidth(55);
    threadSpin->setAlignment(Qt::AlignCenter);

    lblTemp = new QLabel(this);
    tempSpin = new QDoubleSpinBox(this);
    tempSpin->setRange(0, 2);
    tempSpin->setSingleStep(0.1);
    tempSpin->setFixedWidth(55);
    tempSpin->setAlignment(Qt::AlignCenter);

    lblCtx = new QLabel(this);
    contextSpin = new QSpinBox(this);
    contextSpin->setRange(0, 20);
    contextSpin->setFixedWidth(55);
    contextSpin->setAlignment(Qt::AlignCenter);

    clearCtxBtn = new QPushButton(this);
    clearCtxBtn->setFixedWidth(50);
    connect(clearCtxBtn, &QPushButton::clicked, this, &MainWindow::onClearContext);

    lblTokens = new QLabel(this);
    lblTokens->setObjectName("lblTokens"); 

    // 添加参数控件到布局 / Add parameter controls to layout
    paramLayout->addWidget(lblPort);
    paramLayout->addWidget(portEdit);
    paramLayout->addWidget(lblThread);
    paramLayout->addWidget(threadSpin);
    paramLayout->addWidget(lblTemp);
    paramLayout->addWidget(tempSpin);
    paramLayout->addWidget(lblCtx);
    paramLayout->addWidget(contextSpin);
    paramLayout->addWidget(clearCtxBtn);
    paramLayout->addWidget(lblTokens);
    paramLayout->addStretch();

    grid->addWidget(paramContainer, 3, 0, 1, 2);

    // 系统提示词输入框 / System prompt input field
    systemPromptEdit = new QTextEdit(this);
    systemPromptEdit->setMinimumHeight(100); 
    lblSysPrompt = new QLabel(this);
    lblSysPrompt->setAlignment(Qt::AlignRight | Qt::AlignTop);
    grid->addWidget(lblSysPrompt, 4, 0);
    grid->addWidget(systemPromptEdit, 4, 1);

    // 前置文本输入框 / Pre-prompt input field
    prePromptEdit = new QLineEdit(this);
    grid->addWidget(createLabel(lblPrePrompt), 5, 0);
    grid->addWidget(prePromptEdit, 5, 1);

    // 术语表选择区域 / Glossary selection area
    QWidget *glossaryContainer = new QWidget(this);
    QHBoxLayout *glossaryLayout = new QHBoxLayout(glossaryContainer);
    glossaryLayout->setContentsMargins(0, 0, 0, 0);
    
    chkGlossary = new QCheckBox(this);
    
    glossaryCombo = new QComboBox(this);
    glossaryCombo->setEditable(true); 
    glossaryCombo->setMinimumHeight(28);
    glossaryCombo->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Fixed); 
    
    btnOpenAuto = new QPushButton(STR_BTN_AUTO[m_currentLang], this);
    btnOpenAuto->setFixedWidth(50);
    connect(btnOpenAuto, &QPushButton::clicked, this, &MainWindow::onOpenAutoTranslations);

    btnSelectGlossary = new QPushButton("...", this);
    btnSelectGlossary->setFixedWidth(35);
    connect(btnSelectGlossary, &QPushButton::clicked, this, &MainWindow::onSelectGlossary);

    glossaryLayout->addWidget(chkGlossary);
    glossaryLayout->addWidget(glossaryCombo, 1); 
    glossaryLayout->addWidget(btnOpenAuto);
    glossaryLayout->addWidget(btnSelectGlossary);
    
    grid->addWidget(createLabel(lblGlossary), 6, 0);
    grid->addWidget(glossaryContainer, 6, 1);

    // 添加配置组框到主布局 / Add configuration group box to main layout
    mainLayout->addWidget(cfgGroup);

    // === 按钮网格布局 / Buttons Grid Layout ===
    QGridLayout *btnGridLayout = new QGridLayout();
    btnGridLayout->setSpacing(10);
    
    // 按钮创建辅助函数 / Button creation helper function
    auto createBtn = [this] (QPushButton*& btnPtr) {
        btnPtr = new QPushButton(this);
        btnPtr->setMinimumHeight(32);
        btnPtr->setCursor(Qt::PointingHandCursor);
        return btnPtr;
    };

    // 第0行：启动 | 停止 | HUD / Row 0: Start | Stop | HUD
    btnGridLayout->addWidget(createBtn(startBtn), 0, 0);
    startBtn->setObjectName("btnStart"); 

    btnGridLayout->addWidget(createBtn(stopBtn), 0, 1);
    stopBtn->setEnabled(false);
    
    hudBtn = new QPushButton(this);
    hudBtn->setMinimumHeight(32);
    hudBtn->setCursor(Qt::PointingHandCursor);
    hudBtn->setEnabled(false); 
    connect(hudBtn, &QPushButton::clicked, this, &MainWindow::switchToHud);
    btnGridLayout->addWidget(hudBtn, 0, 2);

    // 第1行：测试 | 导出 | 加载 / Row 1: Test | Export | Load
    btnGridLayout->addWidget(createBtn(testBtn), 1, 0);
    btnGridLayout->addWidget(createBtn(exportBtn), 1, 1);
    btnGridLayout->addWidget(createBtn(loadBtn), 1, 2);

    // 第2行：保存 | 主题 | 语言 / Row 2: Save | Theme | Language
    btnGridLayout->addWidget(createBtn(saveBtn), 2, 0);
    btnGridLayout->addWidget(createBtn(themeBtn), 2, 1);
    btnGridLayout->addWidget(createBtn(langBtn), 2, 2);

    // 连接按钮信号 / Connect button signals
    connect(themeBtn, &QPushButton::clicked, this, &MainWindow::toggleTheme);
    connect(langBtn, &QPushButton::clicked, this, &MainWindow::toggleLanguage);
    connect(startBtn, &QPushButton::clicked, this, &MainWindow::onStartClicked);
    connect(stopBtn, &QPushButton::clicked, this, &MainWindow::onStopClicked);
    connect(testBtn, &QPushButton::clicked, this, &MainWindow::onTestConfig);
    connect(loadBtn, &QPushButton::clicked, this, &MainWindow::onLoadConfig);
    connect(saveBtn, &QPushButton::clicked, this, &MainWindow::onSaveConfig);
    connect(exportBtn, &QPushButton::clicked, this, &MainWindow::onExportLog);

    // 添加按钮布局到主布局 / Add button layout to main layout
    mainLayout->addLayout(btnGridLayout);

    // === 日志区域 / Log Area ===
    logGroup = new QGroupBox(this);
    QVBoxLayout *logLayout = new QVBoxLayout(logGroup);
    logLayout->setContentsMargins(10, 20, 10, 10);
    logArea = new QTextEdit(this);
    logArea->setReadOnly(true);
    logArea->setMinimumHeight(150); 
    logArea->setContextMenuPolicy(Qt::CustomContextMenu);
    connect(logArea, &QTextEdit::customContextMenuRequested, this, &MainWindow::onLogContextMenu);
    logLayout->addWidget(logArea);
    mainLayout->addWidget(logGroup);
}

/**
 * 日志区域上下文菜单
 * Log area context menu
 * @param pos 菜单位置 / Menu position
 */
void MainWindow::onLogContextMenu(const QPoint &pos) {
    // 创建标准上下文菜单 / Create standard context menu
    QMenu *menu = logArea->createStandardContextMenu();
    menu->addSeparator();
    
    // 添加清空日志选项 / Add clear log option
    QAction *clearAction = menu->addAction(STR_CLEAR_LOG[m_currentLang]);
    connect(clearAction, &QAction::triggered, logArea, &QTextEdit::clear);
    
    // 显示菜单 / Show menu
    menu->exec(logArea->mapToGlobal(pos));
    delete menu;
}

/**
 * 加载配置到UI
 * Load configuration to UI
 */
void MainWindow::loadConfigToUi() {
    // 从配置文件加载配置 / Load configuration from config file
    AppConfig cfg = ConfigManager::loadConfig();
    
    // 设置各控件值 / Set values for each control
    apiAddressCombo->setCurrentText(cfg.api_address);
    apiKeyEdit->setText(cfg.api_key);
    modelCombo->setCurrentText(cfg.model_name);
    portEdit->setText(QString::number(cfg.port));
    tempSpin->setValue(cfg.temperature);
    contextSpin->setValue(cfg.context_num);
    threadSpin->setValue(cfg.max_threads);
    systemPromptEdit->setText(cfg.system_prompt);
    prePromptEdit->setText(cfg.pre_prompt);
    chkGlossary->setChecked(cfg.enable_glossary);
    
    // 加载术语表历史记录 / Load glossary history
    glossaryCombo->clear();
    if (!cfg.glossary_history.isEmpty()) {
        glossaryCombo->addItems(cfg.glossary_history);
    }
    
    // 设置当前术语表路径 / Set current glossary path
    if (!cfg.glossary_path.isEmpty()) {
        int index = glossaryCombo->findText(cfg.glossary_path);
        if (index != -1) {
            glossaryCombo->setCurrentIndex(index);
        } else {
            addToGlossaryHistory(cfg.glossary_path);
        }
    }
    
    // 设置当前语言 / Set current language
    m_currentLang = cfg.language;
}

/**
 * 从UI获取配置
 * Get configuration from UI
 * @return 应用配置对象 / Application configuration object
 */
AppConfig MainWindow::getUiConfig() {
    AppConfig cfg;
    
    // 从UI控件获取值 / Get values from UI controls
    cfg.api_address = apiAddressCombo->currentText();
    cfg.api_key = apiKeyEdit->text();
    cfg.model_name = modelCombo->currentText();
    cfg.port = portEdit->text().toInt();
    cfg.temperature = tempSpin->value();
    cfg.context_num = contextSpin->value();
    cfg.max_threads = threadSpin->value();
    cfg.system_prompt = systemPromptEdit->toPlainText();
    cfg.pre_prompt = prePromptEdit->text();
    cfg.enable_glossary = chkGlossary->isChecked();
    
    cfg.glossary_path = glossaryCombo->currentText();
    
    // 保存术语表历史记录 / Save glossary history
    QStringList history;
    for(int i = 0; i < glossaryCombo->count(); ++i) {
        history << glossaryCombo->itemText(i);
    }
    cfg.glossary_history = history;

    // 保存当前语言 / Save current language
    cfg.language = m_currentLang;
    
    return cfg;
}

/**
 * 切换控件状态（服务运行时禁用部分控件）
 * Toggle control states (disable some controls when service is running)
 * @param running 是否正在运行 / Whether service is running
 */
void MainWindow::toggleControls(bool running) {
    // 设置按钮状态 / Set button states
    startBtn->setEnabled(!running);
    stopBtn->setEnabled(running);
    
    // 设置API相关控件状态 / Set API related control states
    apiAddressCombo->setEnabled(!running);
    apiKeyEdit->setEnabled(!running);
    
    // 设置服务器参数控件状态 / Set server parameter control states
    portEdit->setEnabled(!running);
    threadSpin->setEnabled(!running);
    
    // 设置术语表相关控件状态 / Set glossary related control states
    chkGlossary->setEnabled(!running);
    glossaryCombo->setEnabled(!running);
    btnSelectGlossary->setEnabled(!running);
    
    // 设置自动翻译按钮状态 / Set auto translation button state
    if(btnOpenAuto) btnOpenAuto->setEnabled(!running); 
    
    // 设置HUD按钮状态 / Set HUD button state
    hudBtn->setEnabled(running);
}

/**
 * 启动按钮点击处理
 * Start button click handler
 */
void MainWindow::onStartClicked() {
    // 获取UI配置并更新服务器配置 / Get UI configuration and update server configuration
    AppConfig cfg = getUiConfig();
    server->updateConfig(cfg);
    
    // 启动服务器 / Start server
    server->startServer();
    
    // 切换控件状态 / Toggle control states
    toggleControls(true); 
}

/**
 * 停止按钮点击处理
 * Stop button click handler
 */
void MainWindow::onStopClicked() {
    // 停止服务器 / Stop server
    server->stopServer();
    
    // 切换控件状态 / Toggle control states
    toggleControls(false); 
}

/**
 * 日志消息处理
 * Log message handler
 * @param msg 日志消息 / Log message
 */
void MainWindow::onLogMessage(QString msg) {
    // 添加消息到日志区域 / Add message to log area
    logArea->append(msg);
    
    // 限制日志行数（避免内存占用过大） / Limit log lines (avoid excessive memory usage)
    const int MAX_LOG_LINES = 2000;
    if (logArea->document()->blockCount() > MAX_LOG_LINES) {
        QTextCursor cursor(logArea->document());
        cursor.movePosition(QTextCursor::Start);
        
        // 删除前500行 / Delete first 500 lines
        for(int i = 0; i < 500; ++i) {
            cursor.movePosition(QTextCursor::NextBlock, QTextCursor::KeepAnchor);
        }
        cursor.removeSelectedText();
    }
}

/**
 * 保存配置按钮点击处理
 * Save configuration button click handler
 */
void MainWindow::onSaveConfig() {
    // 打开文件保存对话框 / Open file save dialog
    QString fileName = QFileDialog::getSaveFileName(this, STR_SAVE[m_currentLang], "config.ini", "Config Files (*.ini)");
    
    // 如果选择了文件，保存配置 / If file selected, save configuration
    if (!fileName.isEmpty()) {
        ConfigManager::saveConfig(getUiConfig(), fileName);
        logArea->append(QString(LOG_CFG_SAVED[m_currentLang]) + fileName);
    }
}

/**
 * 加载配置按钮点击处理
 * Load configuration button click handler
 */
void MainWindow::onLoadConfig() {
    // 打开文件选择对话框 / Open file selection dialog
    QString fileName = QFileDialog::getOpenFileName(this, STR_LOAD[m_currentLang], "", "Config Files (*.ini)");
    
    // 如果选择了文件，加载配置并更新UI / If file selected, load configuration and update UI
    if (!fileName.isEmpty()) {
        AppConfig cfg = ConfigManager::loadConfig(fileName);
        
        // 更新UI控件值 / Update UI control values
        apiAddressCombo->setCurrentText(cfg.api_address);
        apiKeyEdit->setText(cfg.api_key);
        modelCombo->setCurrentText(cfg.model_name);
        portEdit->setText(QString::number(cfg.port));
        tempSpin->setValue(cfg.temperature);
        contextSpin->setValue(cfg.context_num);
        threadSpin->setValue(cfg.max_threads);
        systemPromptEdit->setText(cfg.system_prompt);
        prePromptEdit->setText(cfg.pre_prompt);
        chkGlossary->setChecked(cfg.enable_glossary);
        
        // 加载术语表历史记录 / Load glossary history
        glossaryCombo->clear();
        if (!cfg.glossary_history.isEmpty()) {
            glossaryCombo->addItems(cfg.glossary_history);
        }
        
        // 设置当前术语表路径 / Set current glossary path
        if (!cfg.glossary_path.isEmpty()) {
            int index = glossaryCombo->findText(cfg.glossary_path);
            if (index != -1) glossaryCombo->setCurrentIndex(index);
            else addToGlossaryHistory(cfg.glossary_path);
        }
        
        // 添加加载成功日志 / Add load success log
        logArea->append(QString(LOG_CFG_LOADED[m_currentLang]) + fileName);
    }
}

/**
 * 导出日志按钮点击处理
 * Export log button click handler
 */
void MainWindow::onExportLog() {
    // 设置导出文件名 / Set export file name
    QString fileName = "run_log.txt";
    QFile file(fileName);
    
    // 打开文件并写入日志内容 / Open file and write log content
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&file);
        
        // 设置UTF-8编码 / Set UTF-8 encoding
        #if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
            out.setEncoding(QStringConverter::Utf8);
        #else
            out.setCodec("UTF-8");
        #endif
        
        // 写入日志内容 / Write log content
        out << logArea->toPlainText();
        
        // 添加导出成功日志消息 / Add export success log message
        logArea->append(LOG_EXPORTED[m_currentLang]);
    }
}

/**
 * 获取模型列表
 * Fetch models list
 */
void MainWindow::onFetchModels() {
    // 构建模型列表请求URL / Build models list request URL
    QString url = apiAddressCombo->currentText();
    
    // 确保URL格式正确 / Ensure correct URL format
    if(url.endsWith("/")) url.chop(1);
    url += "/models";
    
    // 创建网络访问管理器 / Create network access manager
    QNetworkAccessManager *mgr = new QNetworkAccessManager(this);
    QNetworkRequest req(url);
    
    // 设置授权头（支持多key格式） / Set authorization header (support multi-key format)
    QString key = apiKeyEdit->text().split(',')[0].trimmed();
    req.setRawHeader("Authorization", ("Bearer " + key).toUtf8());
    
    // 发送GET请求 / Send GET request
    QNetworkReply *reply = mgr->get(req);
    
    // 请求完成处理 / Request completion handling
    connect(reply, &QNetworkReply::finished, [this, reply, mgr](){
        if(reply->error() == QNetworkReply::NoError) {
            try {
                // 解析JSON响应 / Parse JSON response
                auto jsonDoc = nlohmann::json::parse(reply->readAll().toStdString());
                
                // 清空现有模型列表 / Clear existing model list
                modelCombo->clear();
                
                // 添加新模型到下拉框 / Add new models to combobox
                for(const auto& item : jsonDoc["data"]) {
                    modelCombo->addItem(QString::fromStdString(item["id"]));
                }
                
                // 添加成功日志 / Add success log
                logArea->append(LOG_FETCH_SUCCESS[m_currentLang]);
            } catch(...) {
                // 解析错误处理 / Parse error handling
                logArea->append(LOG_PARSE_ERR[m_currentLang]);
            }
        } else {
            // 请求失败处理 / Request failure handling
            logArea->append(QString(LOG_FETCH_FAIL[m_currentLang]) + reply->errorString());
        }
        
        // 清理资源 / Clean up resources
        reply->deleteLater();
        mgr->deleteLater();
    });
}

/**
 * 测试配置按钮点击处理
 * Test configuration button click handler
 */
void MainWindow::onTestConfig() {
    // 添加测试开始日志 / Add test start log
    logArea->append(LOG_TEST_START[m_currentLang]);
    
    // 解析API密钥（支持多个密钥） / Parse API keys (support multiple keys)
    QStringList keys = apiKeyEdit->text().split(',', Qt::SkipEmptyParts);
    
    // 检查是否有API密钥 / Check if API keys exist
    if (keys.isEmpty()) {
        logArea->append(LOG_NO_KEY[m_currentLang]);
        return;
    }
    
    // 构建测试请求URL / Build test request URL
    QString url = apiAddressCombo->currentText();
    
    // 确保URL格式正确 / Ensure correct URL format
    if(url.endsWith("/")) url.chop(1);
    url += "/chat/completions";
    
    // 获取当前选择的模型 / Get currently selected model
    QString model = modelCombo->currentText();

    // 测试每个API密钥 / Test each API key
    for (int i = 0; i < keys.size(); ++i) {
        QString key = keys[i].trimmed();
        
        // 创建密钥掩码（保护隐私） / Create key mask (privacy protection)
        QString keyMasked = (key.length() > 8) ? ("..." + key.right(8)) : key;
        
        // 创建网络访问管理器 / Create network access manager
        QNetworkAccessManager *mgr = new QNetworkAccessManager(this);
        QNetworkRequest req(url);
        
        // 设置请求头 / Set request headers
        req.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
        req.setRawHeader("Authorization", ("Bearer " + key).toUtf8());
        
        // 构建测试请求JSON / Build test request JSON
        nlohmann::json j;
        j["model"] = model.toStdString();
        j["messages"] = nlohmann::json::array({{{"role", "user"}, {"content", "Hi"}}});
        j["max_tokens"] = 5;
        
        // 发送POST请求 / Send POST request
        QNetworkReply *reply = mgr->post(req, QByteArray::fromStdString(j.dump()));
        
        // 请求完成处理 / Request completion handling
        connect(reply, &QNetworkReply::finished, [this, reply, mgr, keyMasked, i](){
            if(reply->error() == QNetworkReply::NoError) {
                // 测试通过 / Test passed
                logArea->append(QString("✅ Key-%1 (%2): %3").arg(i+1).arg(keyMasked).arg(LOG_PASS[m_currentLang]));
            } else {
                // 测试失败 / Test failed
                logArea->append(QString("❌ Key-%1 (%2): %3 - %4").arg(i+1).arg(keyMasked).arg(LOG_FAIL[m_currentLang]).arg(reply->errorString()));
            }
            
            // 清理资源 / Clean up resources
            reply->deleteLater();
            mgr->deleteLater();
        });
    }
}

/**
 * 更新Token显示
 * Update token display
 * @param total 总token数 / Total tokens
 * @param prompt 输入token数 / Input tokens
 * @param completion 输出token数 / Output tokens
 */
void MainWindow::updateTokenDisplay(long long total, long long prompt, long long completion) {
    // 更新总token显示 / Update total token display
    lblTokens->setText(QString("%1 %2").arg(STR_TOKENS[m_currentLang]).arg(total));
    
    // 更新详细提示信息 / Update detailed tooltip information
    lblTokens->setToolTip(QString("Input: %1\nOutput: %2").arg(prompt).arg(completion));
}

/**
 * 清除上下文按钮点击处理
 * Clear context button click handler
 */
void MainWindow::onClearContext() {
    // 清除所有对话上下文 / Clear all conversation contexts
    server->clearAllContexts();
}

/**
 * 切换到HUD模式
 * Switch to HUD mode
 */
void MainWindow::switchToHud() {
    // 检查服务器是否存在 / Check if server exists
    if (!server) return;
    
    // 创建淡出动画 / Create fade out animation
    QPropertyAnimation *anim = new QPropertyAnimation(this, "windowOpacity");
    anim->setDuration(300);
    anim->setStartValue(1.0);
    anim->setEndValue(0.0);
    
    // 动画完成处理 / Animation completion handling
    connect(anim, &QPropertyAnimation::finished, [this](){
        // 隐藏主窗口 / Hide main window
        this->hide();
        
        // 设置HUD窗口位置并显示 / Set HUD window position and show
        m_hudWindow->move(this->geometry().topRight() - QPoint(280, -20)); 
        m_hudWindow->show();
        
        // 设置HUD窗口状态 / Set HUD window status
        m_hudWindow->setStatus(false);
        
        // 更新HUD窗口Token显示 / Update HUD window token display
        m_hudWindow->updateTokens(m_tokenManager->getTotal());
    });
    
    // 启动动画 / Start animation
    anim->start(QAbstractAnimation::DeleteWhenStopped);
}

/**
 * 从HUD模式恢复主窗口
 * Restore main window from HUD mode
 */
void MainWindow::restoreFromHud() {
    // 隐藏HUD窗口 / Hide HUD window
    m_hudWindow->hide();
    
    // 设置主窗口透明度并显示 / Set main window opacity and show
    this->setWindowOpacity(0.0);
    this->show();
    
    // 创建淡入动画 / Create fade in animation
    QPropertyAnimation *anim = new QPropertyAnimation(this, "windowOpacity");
    anim->setDuration(300);
    anim->setStartValue(0.0);
    anim->setEndValue(1.0);
    
    // 启动动画 / Start animation
    anim->start(QAbstractAnimation::DeleteWhenStopped);
}

/**
 * 服务器工作开始处理
 * Server work started handler
 */
void MainWindow::onServerWorkStarted() {
    // 如果HUD窗口可见，设置忙碌状态 / If HUD window is visible, set busy status
    if (m_hudWindow && m_hudWindow->isVisible()) {
        m_hudWindow->setStatus(true);
    }
}

/**
 * 服务器工作完成处理
 * Server work finished handler
 * @param success 是否成功 / Whether operation succeeded
 */
void MainWindow::onServerWorkFinished(bool success) {
    // 如果HUD窗口可见，设置空闲状态 / If HUD window is visible, set idle status
    if (m_hudWindow && m_hudWindow->isVisible()) {
        m_hudWindow->setStatus(false, !success); 
    }
}