/**
 * MainWindow.cpp - Moil's XUnity LLM Translator GUI Implementation
 * MainWindow.cpp - Moil的XUnity大模型翻译器GUI实现
 * 
 * Final Perfect Version by CAN.
 * Base: MainWindow.txt (Preferred UI/UX)
 * Core Logic: 1.txt (Robust Hot Reload & Layout Fixes)
 * Updated: Logic Fixed - User Lock Override (Session Persistence)
 */

#include "MainWindow.h"
#include "json.hpp"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QGroupBox>
#include <QFileDialog>
#include <QMessageBox>
#include <QApplication>
#include <QFile>
#include <QTextStream>
#include <QCloseEvent>
#include <QStyleFactory>
#include <QPixmap>
#include <QMenu>
#include <QScrollBar>
#include <QGraphicsOpacityEffect>
#include <QPropertyAnimation>
#include <QListView> 
#include <QDesktopServices>
#include <QUrl>
#include <QFileInfo>

// ==========================================
// 🌍 多语言字典定义 (UI Text)
// ==========================================

// Window titles / 窗口标题
const char* STR_TITLE[] = {"Moil's XUnity LLM Translator", "Moil的XUnity大模型翻译GUI"};

// Configuration section titles / 配置部分标题
const char* STR_API_CFG[] = {"API Configuration", "API 配置"};
const char* STR_LOG_AREA[] = {"Runtime Logs", "运行日志"};

// API configuration related text / API配置相关文本
const char* STR_API_ADDR[] = {"API Address:", "API 地址:"};
const char* STR_API_KEY[] = {"API Key:", "API 密钥:"};
const char* STR_MODEL[] = {"Model Name:", "模型名称:"};
const char* STR_FETCH[] = {"Fetch", "获取"};

// Server parameter text / 服务器参数文本
const char* STR_PORT[] = {"Port:", "端口:"};
const char* STR_THREAD[] = {"Threads:", "线程:"};
const char* STR_TEMP[] = {"Temp:", "温度:"};
const char* STR_CTX[] = {"Context:", "上下文:"};

// Prompt related text / 提示词相关文本
const char* STR_SYS_PROMPT[] = {"System Prompt:", "系统提示:"};
const char* STR_PRE_PROMPT[] = {"Pre-Prompt:", "前置文本:"};

// Control button text / 控制按钮文本
const char* STR_START[] = {"Start Service", "启动服务"};
const char* STR_RELOAD[] = {"Hot Reload", "热重载配置"}; 
const char* STR_STOP[] = {"Stop Service", "停止服务"};
const char* STR_HUD[] = {"HUD Mode", "HUD 模式"};
const char* STR_TEST[] = {"Test Config", "测试配置"};
const char* STR_LOAD[] = {"Load Config", "读取配置"};
const char* STR_SAVE[] = {"Save Config", "保存配置"};
const char* STR_EXPORT[] = {"Export Log", "导出日志"};

// Theme and language text / 主题和语言文本
const char* STR_THEME_LIGHT[] = {"Light Mode", "切换亮色"};
const char* STR_THEME_DARK[] = {"Dark Mode", "切换暗色"};
const char* STR_LANG_BTN[] = {"中文", "English"}; 

// Glossary related text / 术语表相关文本
const char* STR_GLOSSARY[] = {"Glossary:", "术语表:"};
const char* STR_CHK_GLOSSARY[] = {"Self-Evolve", "启用自进化"};
const char* STR_CLEAR_LOG[] = {"Clear Log", "清空日志"};
const char* STR_REMOVE_PATH[] = {"Remove Current Path", "移除当前路径"};
const char* STR_CLEAR_HISTORY[] = {"Clear All History", "清空历史记录"};

// Token statistics text / Token统计文本
const char* STR_TOKENS[] = {"Tokens:", "消耗:"};
const char* TIP_TOKENS[] = {"Total Usage (Prompt + Completion)", "本次运行总消耗 (输入+输出)"};

// Context clearing related text / 上下文清除相关文本
const char* STR_CLEAR_CTX[] = {"Clear", "清空"};
const char* TIP_CLEAR_CTX[] = {"Clear Context", "清除历史对话记忆"};

// New button text / 新按钮文本
const char* STR_BTN_AUTO[] = {"Edit", "编辑"};
const char* TIP_BTN_AUTO[] = {
    "Open _AutoGeneratedTranslations.txt in same folder", 
    "打开同目录下的 _AutoGeneratedTranslations.txt (自动翻译结果)"
};

// 
const char* STR_LOCK_SYS[] = {"Lock", "锁定"};
const char* TIP_LOCK_SYS[] = {
    "Lock System Prompt to prevent overwriting when loading config", 
    "锁定系统提示词，防止在读取配置时被覆盖"
};

// ==========================================
// 📝 日志消息定义 (Logs - Merged for Completeness)
// ==========================================

const char* LOG_TEST_START[] = {"📡 === Testing API Keys ===", "📡 === 开始测试所有 API Key ==="};
const char* LOG_NO_KEY[] = {"❌ No API Key", "❌ 未找到 API Key"};
const char* LOG_PASS[] = {"Pass", "测试通过"};
const char* LOG_FAIL[] = {"Fail", "失败"};
const char* LOG_FETCH_SUCCESS[] = {"Fetch Models Success", "模型列表获取成功"};
const char* LOG_FETCH_FAIL[] = {"Fetch Failed: ", "获取失败: "};
const char* LOG_PARSE_ERR[] = {"Parse Error", "解析错误"};
const char* LOG_CFG_SAVED[] = {"⚙️ Config Saved: ", "⚙️ 配置已保存: "};
const char* LOG_CFG_LOADED[] = {"📙 Config Loaded: ", "📙 配置已加载: "};
const char* LOG_EXPORTED[] = {"✒️ Log Exported to run_log.txt", "✒️ 日志已导出到 run_log.txt"};

// 🔥 Enhanced Hot Reload Logs (From 1.txt) / 增强的热重载日志（来自1.txt）
const char* LOG_RELOADED[] = {"⚡ Config Hot Reloaded!", "⚡ 配置已热重载生效！"};
const char* LOG_MODEL_SWITCH[] = {"🔄 Model Switch: [%1] -> [%2]", "🔄 模型切换: [%1] -> [%2]"};
const char* LOG_MODEL_SAME[] = {"⚡ Reloaded (Model: %1)", "⚡ 热重载成功 (模型: %1)"};
const char* LOG_AUTO_TESTING[] = {"🛠️ Auto-testing new config...", "🛠️ 正在自动测试新配置..."};

// ==========================================
// 💡 详细工具提示 (Detailed Tooltips)
// ==========================================

const char* TIP_PORT[] = {
    "Local Listening Port (Restart required to change)\nEnsure XUnity Endpoint is set to http://localhost:port",
    "本地监听端口 (修改需重启服务)\n请确保 XUnity 配置文件 Endpoint 设置为 http://localhost:端口号"
};

const char* TIP_THREAD[] = {
    "Concurrent Threads\nRecommended: Depends on your CPU\nNote: Can speed up translation to some extent, too many may cause system lag",
    "并发线程数 (Max Threads)\n建议值: 取决于你电脑的线程数\n注意: 一定程度上可以加快翻译工作，过多会导致系统卡顿"
};

const char* TIP_TEMP[] = {
    "Sampling Temperature\n0.0-0.3: Strict\n0.7-1.0: Standard\n>1.0: Creative/Random",
    "采样温度 (Temperature)\n0.0-0.3: 严谨\n0.7-1.0: 标准\n>1.0: 随机/创造性"
};

const char* TIP_CTX[] = {
    "Context Memory\nNumber of history turns to carry.\nNote: More context consumes more tokens.",
    "上下文记忆 (Context)\n携带的历史对话轮数。\n注意：上下文越多，消耗 Token 越多。"
};

const char* TIP_GLOSSARY[] = {
    "Select XUnity's _Substitutions.txt.\nLLM will reference and append to it.",
    "选择 XUnity 的 _Substitutions.txt 文件。\nLLM 将自动参考并补充该文件。"
};

const char* TIP_COMBO_MAIN[] = {
    "Enter API Address or select from list.\nMust support /v1/chat/completions format.",
    "在此输入 API 地址，或从下拉列表中选择主流服务商。\n所有地址必须兼容 OpenAI 接口格式 (/v1/chat/completions)。"
};

// ==========================================
// ⚙️ API Presets
// ==========================================

struct ApiPresetDef {
    const char* url;          // API URL / API地址
    const char* tips[2];      // Tooltip text in both languages / 双语工具提示文本
};

const ApiPresetDef PRESETS_DATA[] = {
    {"https://api.openai.com/v1", {"OpenAI Official API", "OpenAI 官方接口"}},
    {"https://api.deepseek.com", {"DeepSeek Official API", "DeepSeek 官方接口"}},
    {"https://api.x.ai/v1", {"Grok (xAI) Official API", "Grok (xAI) 官方接口"}},
    {"https://api.siliconflow.cn/v1", {"SiliconFlow", "硅基流动 (SiliconFlow)"}},
    {"https://openrouter.ai/api/v1", {"OpenRouter Aggregator", "OpenRouter 聚合平台"}},
    {"https://generativelanguage.googleapis.com/v1beta/openai", {"Google Gemini", "Google Gemini (OpenAI 兼容端点)"}},
    {"http://localhost:11434/v1", {"Ollama Local Service", "Ollama 本地服务"}},
    {"http://localhost:1234/v1", {"LM Studio Local Service", "LM Studio 本地服务"}}
};

// ==========================================
// 🚀 Implementation
// ==========================================

MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent) {
    // Initialize member variables / 初始化成员变量
    m_isClosing = false;          // Flag to prevent multiple close events / 防止多次关闭事件的标志
    m_isDarkTheme = true;         // Default to dark theme / 默认为暗色主题
    m_currentLang = 1;            // Default to Chinese / 默认中文
    m_isServerRunning = false;    // Server is not running initially / 服务器初始状态为未运行

    // Initial size - restored to compact width / 初始大小 - 恢复为紧凑宽度
    resize(400, 800);

    // Create core components / 创建核心组件
    m_tokenManager = new TokenManager(this);
    server = new TranslationServer(this);
    m_hudWindow = new HudWindow(nullptr);
    
    // Setup user interface / 设置用户界面
    setupUi();

    // Connect signals and slots / 连接信号和槽
    connect(server, &TranslationServer::logMessage, this, &MainWindow::onLogMessage);
    connect(server, &TranslationServer::tokenUsageReceived, m_tokenManager, &TokenManager::addUsage);
    connect(m_tokenManager, &TokenManager::tokensUpdated, this, &MainWindow::updateTokenDisplay);

    connect(m_hudWindow, &HudWindow::requestRestore, this, &MainWindow::restoreFromHud);
    connect(m_tokenManager, &TokenManager::tokensUpdated,  [this](long long t, long long, long long){
        if(m_hudWindow) m_hudWindow->updateTokens(t);
    });
    
    connect(server, &TranslationServer::workStarted, this, &MainWindow::onServerWorkStarted);
    connect(server, &TranslationServer::workFinished, this, &MainWindow::onServerWorkFinished);

    // Load configuration and apply theme / 加载配置并应用主题
    loadConfigToUi();
    updateUIText();
    applyTheme(true); 

    // Fade-in animation / 淡入动画
    setWindowOpacity(0.0);
    fadeAnim = new QPropertyAnimation(this, "windowOpacity");
    fadeAnim->setDuration(500);
    fadeAnim->setStartValue(0.0);
    fadeAnim->setEndValue(1.0);
    fadeAnim->start();
}

MainWindow::~MainWindow() {
    // Clean up resources / 清理资源
    if (m_hudWindow) {
        m_hudWindow->close();
        delete m_hudWindow;
    }
    server->stopServer();
}

void MainWindow::closeEvent(QCloseEvent *event) {
    if (m_isClosing) {
        event->accept();
        return;
    }
    
    // Save configuration before closing / 关闭前保存配置
    ConfigManager::saveConfig(getUiConfig(), "config.ini");
    

    // 🔥 CAN: 独立保存术语表锁定状态
    QSettings sess("config.ini", QSettings::IniFormat);
    sess.setValue("Settings/lock_glossary_path", chkLockGlossary->isChecked());
    sess.sync();

    if (m_hudWindow->isVisible()) {
        m_hudWindow->close();
    }
    
    event->ignore();
    m_isClosing = true;
    fadeOutAndClose();
}

void MainWindow::fadeOutAndClose() {
    // Reverse the fade animation for smooth exit / 反向淡出动画实现平滑退出
    fadeAnim->setDirection(QAbstractAnimation::Backward);
    connect(fadeAnim, &QPropertyAnimation::finished, this, &QMainWindow::close);
    connect(fadeAnim, &QPropertyAnimation::finished, qApp, &QApplication::quit);
    fadeAnim->start();
}

void MainWindow::smoothSwitch(std::function<void()> changeLogic) {
    /**
     * Perform a smooth visual transition when changing UI state / 在更改UI状态时执行平滑视觉过渡
     * @param changeLogic: The actual UI change to perform / 要执行的实际UI更改逻辑
     */
    
    // Capture current screen / 捕获当前屏幕
    QPixmap pixmap = this->grab();
    QLabel* overlay = new QLabel(this);
    overlay->setPixmap(pixmap);
    overlay->setGeometry(0, 0, this->width(), this->height());
    overlay->show();

    // Execute the change logic / 执行更改逻辑
    changeLogic();

    // Apply fade-out animation to overlay / 对覆盖层应用淡出动画
    QGraphicsOpacityEffect* effect = new QGraphicsOpacityEffect(overlay);
    overlay->setGraphicsEffect(effect);

    QPropertyAnimation* anim = new QPropertyAnimation(effect, "opacity");
    anim->setDuration(300);
    anim->setStartValue(1.0);
    anim->setEndValue(0.0);
    
    connect(anim, &QPropertyAnimation::finished, overlay, &QLabel::deleteLater);
    anim->start(QAbstractAnimation::DeleteWhenStopped);
}

void MainWindow::toggleLanguage() {
    // 💡 1. First save the current complete configuration copy / 先保存当前完整配置副本
    AppConfig currentCfg = getUiConfig(); 

    smoothSwitch([this, currentCfg](){
        // 💡 2. Switch language flag / 切换语言标志位
        m_currentLang = (m_currentLang == 0) ? 1 : 0;
        
        // 💡 3. Update UI text (blocker already added internally) / 更新 UI 文字（内部已加 blocker）
        updateUIText();
        
        // 💡 4. The processing here is critical: / 这里的处理很关键：
        // After updateUIText finishes, we need to ensure apiAddressCombo restores correctly
        // Since we already have currentCfg, directly use its value to restore
        // updateUIText 结束后，我们需要确保 apiAddressCombo 恢复正确
        // 既然我们已经有了 currentCfg，直接用它的值恢复
        apiAddressCombo->setCurrentText(currentCfg.api_address);

        if(themeBtn) themeBtn->setText(m_isDarkTheme ? STR_THEME_LIGHT[m_currentLang] : STR_THEME_DARK[m_currentLang]);
        toggleControls(m_isServerRunning);
        
        // 💡 5. Update server configuration / 更新服务器配置
        // At this point, currentCfg's language is still old, we need to update it before giving it to the server
        // 此时 currentCfg 的 language 还是旧的，我们需要更新它再交给服务器
        AppConfig finalCfg = currentCfg;
        finalCfg.language = m_currentLang;
        server->updateConfig(finalCfg);

        qApp->processEvents();
        adjustSize();
        resize(400, 800); 
    });
}

void MainWindow::toggleTheme() {
    smoothSwitch([this](){
        applyTheme(!m_isDarkTheme);
        toggleControls(m_isServerRunning);
    });
}

void MainWindow::addToGlossaryHistory(const QString& path) {
    if (path.isEmpty()) return;
    
    // Extract current history items
    QStringList items;
    for (int i = 0; i < glossaryCombo->count(); ++i) {
        items << glossaryCombo->itemText(i);
    }
    
    // Remove duplicates and add new path to top
    items.removeAll(path);
    items.insert(0, path);
    
    // Limit history size to 10 items
    while (items.size() > 10) {
        items.removeLast();
    }
    
    // Update combo box
    glossaryCombo->clear();
    glossaryCombo->addItems(items);
    glossaryCombo->setCurrentIndex(0); 
    
    // 🔥 CAN: 强制将光标移到最左侧 (Focus on Start)
    if (glossaryCombo->lineEdit()) {
        glossaryCombo->lineEdit()->setCursorPosition(0);
    }
}

void MainWindow::onSelectGlossary() {
    QString fileName = QFileDialog::getOpenFileName(this, tr("Select Glossary"), "", "XUnity Files (*.txt);;All Files (*)");
    
    if (!fileName.isEmpty()) {
        addToGlossaryHistory(fileName); // 内部应处理 glossaryCombo->insertItem 并 setCurrentText
        
        // 如果服务器在运行，执行“即时生效”逻辑
        if (m_isServerRunning && server) {
            AppConfig cfg = getUiConfig();
            server->updateConfig(cfg);
            onLogMessage(m_currentLang == 0 ? "✅ New glossary applied." : "✅ 新术语表已应用。");
        }
    }
}

void MainWindow::onOpenAutoTranslations() {
    // Get current glossary file path / 获取当前术语表文件路径
    QString currentPath = glossaryCombo->currentText();
    if (currentPath.isEmpty()) return;

    // Construct path to auto-generated translations file / 构造自动生成的翻译文件路径
    QFileInfo fi(currentPath);
    QString dir = fi.absolutePath();
    QString targetFile = dir + "/_AutoGeneratedTranslations.txt";

    QFileInfo targetFi(targetFile);
    if (!targetFi.exists()) {
        // File doesn't exist, show warning / 文件不存在，显示警告
        QMessageBox::warning(this, 
            (m_currentLang == 1 ? "文件未找到" : "File Not Found"), 
            (m_currentLang == 1 ? "未找到 _AutoGeneratedTranslations.txt。\n请确认游戏是否已经运行并生成了翻译。" : 
            "Could not find _AutoGeneratedTranslations.txt.\nPlease ensure the game has run and generated translations."));
        return;
    }
    
    // Open file with default application / 使用默认应用程序打开文件
    QDesktopServices::openUrl(QUrl::fromLocalFile(targetFile));
}

void MainWindow::updateUIText() {
    int i = m_currentLang;

    // 💡 Lock current API address and combo box state to prevent jumping during update
    // 锁定当前 API 地址和下拉框状态，防止更新时跳变
    QString currentApi = apiAddressCombo->currentText();
    QSignalBlocker blocker(apiAddressCombo); // Block all signals triggered by modifications / 阻止所有因修改而触发的信号

    // Update window title / 更新窗口标题
    setWindowTitle(STR_TITLE[i]);
    
    // Update group box titles / 更新分组框标题
    cfgGroup->setTitle(STR_API_CFG[i]);
    logGroup->setTitle(STR_LOG_AREA[i]);

    // Update labels / 更新标签
    lblApiAddr->setText(STR_API_ADDR[i]);
    lblApiKey->setText(STR_API_KEY[i]);
    lblModel->setText(STR_MODEL[i]);
    fetchModelBtn->setText(STR_FETCH[i]);

    lblPort->setText(STR_PORT[i]);
    lblThread->setText(STR_THREAD[i]);
    lblTemp->setText(STR_TEMP[i]);
    lblCtx->setText(STR_CTX[i]);
    
    lblSysPrompt->setText(STR_SYS_PROMPT[i]);

    // ✅ Update new lock system prompt checkbox text / 更新新增锁定系统提示词复选框文本
    chkLockSysPrompt->setText(STR_LOCK_SYS[i]);
    chkLockSysPrompt->setToolTip(TIP_LOCK_SYS[i]);

    lblPrePrompt->setText(STR_PRE_PROMPT[i]);

    clearCtxBtn->setText(STR_CLEAR_CTX[i]);
    clearCtxBtn->setToolTip(TIP_CLEAR_CTX[i]);

    lblGlossary->setText(STR_GLOSSARY[i]);
    chkGlossary->setText(STR_CHK_GLOSSARY[i]);

    // Update button text based on server state / 根据服务器状态更新按钮文本
    if (m_isServerRunning) {
        startBtn->setText(STR_RELOAD[i]);
    } else {
        startBtn->setText(STR_START[i]);
    }

    stopBtn->setText(STR_STOP[i]);
    hudBtn->setText(STR_HUD[i]); 
    testBtn->setText(STR_TEST[i]);
    loadBtn->setText(STR_LOAD[i]);
    saveBtn->setText(STR_SAVE[i]);
    exportBtn->setText(STR_EXPORT[i]);
    langBtn->setText(STR_LANG_BTN[i]);

    // Update glossary open button / 更新术语表打开按钮
    if (btnOpenAuto) {
        btnOpenAuto->setText(STR_BTN_AUTO[i]);
        btnOpenAuto->setToolTip(TIP_BTN_AUTO[i]);
    }

    // Update tooltips / 更新工具提示
    portEdit->setToolTip(TIP_PORT[i]);
    lblPort->setToolTip(TIP_PORT[i]);
    threadSpin->setToolTip(TIP_THREAD[i]);
    lblThread->setToolTip(TIP_THREAD[i]);
    tempSpin->setToolTip(TIP_TEMP[i]);
    lblTemp->setToolTip(TIP_TEMP[i]);
    contextSpin->setToolTip(TIP_CTX[i]);
    lblCtx->setToolTip(TIP_CTX[i]);

    lblGlossary->setToolTip(TIP_GLOSSARY[i]);
    chkGlossary->setToolTip(TIP_GLOSSARY[i]);
    btnSelectGlossary->setToolTip(TIP_GLOSSARY[i]);
    if (glossaryCombo) glossaryCombo->setToolTip(TIP_GLOSSARY[i]);
    
    hudBtn->setToolTip(i==0 ? "Switch to Mini-HUD mode" : "切换至迷你悬浮窗模式");
    
    // Update API address combo box tooltips / 更新API地址组合框工具提示
    if (apiAddressCombo) {
        apiAddressCombo->setToolTip(TIP_COMBO_MAIN[i]);
        for (int k = 0; k < apiAddressCombo->count(); ++k) {
            QString itemUrl = apiAddressCombo->itemText(k);
            for (const auto& preset : PRESETS_DATA) {
                if (itemUrl == preset.url) {
                    apiAddressCombo->setItemData(k, preset.tips[i], Qt::ToolTipRole);
                    break;
                }
            }
        }
        // 💡 Force restore original text to prevent changing to preset first item or random item
        // 强制恢复原来的文本，防止变成预设的第一项或随机项
        apiAddressCombo->setCurrentText(currentApi);
    }

    // 💡 Fix: Restore data from properties and refresh display
    // 修正：从属性中恢复数据并刷新显示
    long long t = lblTokens->property("total").toLongLong();
    long long p = lblTokens->property("prompt").toLongLong();
    long long c = lblTokens->property("completion").toLongLong();
    
    // Call modified function to refresh text and Tooltip in one go
    // 调用刚才修改过的函数，一键刷新文字和 Tooltip
    updateTokenDisplay(t, p, c);

    // Update lock glossary checkbox text / 更新锁定术语表复选框文本
    chkLockGlossary->setText(STR_LOCK_SYS[i]);
    chkLockGlossary->setToolTip(i == 1 ? "锁定术语表路径，防止读取配置时被覆盖" : "Lock Glossary Path to prevent overwriting");
}

void MainWindow::applyTheme(bool isDark) {
    // Set Fusion style for consistent look across platforms / 设置Fusion风格以实现跨平台一致外观
    qApp->setStyle(QStyleFactory::create("Fusion"));
    
    QColor windowColor, baseColor, textColor, btnColor, highlightColor, linkColor;
    QString qssBtnBorder, qssBtnBg, qssBtnHover;
    QString dropDownBg, dropDownHover; 
    
    // Set color scheme based on theme / 根据主题设置配色方案
    if (isDark) {
        // Dark theme colors / 暗色主题颜色
        windowColor = QColor(30, 30, 30);    
        baseColor   = QColor(37, 37, 38);   
        textColor   = QColor(220, 220, 220); 
        btnColor    = QColor(60, 60, 60);    
        highlightColor = QColor(0, 122, 204); 
        linkColor   = QColor(86, 156, 214);
        qssBtnBorder = "#555555";
        qssBtnBg     = "#3C3C3C";
        qssBtnHover  = "#505050";
        dropDownBg    = "#C0C0C0"; 
        dropDownHover = "#FFFFFF"; 
        if(themeBtn) themeBtn->setText(STR_THEME_LIGHT[m_currentLang]);
    } else {
        // Light theme colors / 亮色主题颜色
        windowColor = QColor(240, 240, 240);
        baseColor   = QColor(255, 255, 255); 
        textColor   = QColor(0, 0, 0);
        btnColor    = QColor(225, 225, 225);
        highlightColor = QColor(0, 120, 215);
        linkColor   = QColor(0, 0, 255);
        qssBtnBorder = "#C0C0C0";
        qssBtnBg     = "#E1E1E1";
        qssBtnHover  = "#D0D0D0";
        dropDownBg    = "#4D4D4D"; 
        dropDownHover = "#2D2D2D"; 
        if(themeBtn) themeBtn->setText(STR_THEME_DARK[m_currentLang]);
    }
    
    // Apply palette colors / 应用调色板颜色
    QPalette p;
    p.setColor(QPalette::Window, windowColor);
    p.setColor(QPalette::WindowText, textColor);
    p.setColor(QPalette::Base, baseColor); 
    p.setColor(QPalette::AlternateBase, windowColor);
    p.setColor(QPalette::ToolTipBase, baseColor);
    p.setColor(QPalette::ToolTipText, textColor);
    p.setColor(QPalette::Text, textColor);
    p.setColor(QPalette::Button, btnColor);
    p.setColor(QPalette::ButtonText, textColor);
    p.setColor(QPalette::Link, linkColor);
    p.setColor(QPalette::Highlight, highlightColor);
    p.setColor(QPalette::HighlightedText, Qt::white);
    qApp->setPalette(p);
    
    // Apply CSS stylesheet for detailed styling / 应用CSS样式表进行详细样式设置
    QString qss = QString(R"(
        QGroupBox { border: 1px solid %1; border-radius: 5px; margin-top: 1.2em; font-weight: bold; }
        QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; left: 10px; padding: 0 3px; color: %6; }
        QPushButton { border: 1px solid %3; border-radius: 4px; background-color: %4; padding: 5px; font-weight: bold; }
        QPushButton:hover { background-color: %5; border-color: %2; }
        QPushButton:pressed { background-color: %2; color: white; border-color: %2; }
        QPushButton:disabled { background-color: transparent; border: 1px solid %1; color: gray; }
        
        QLineEdit, QComboBox { border: 1px solid %3; border-radius: 4px; background-color: %7; padding: 4px; color: palette(text); selection-background-color: %2; }
        QComboBox:hover, QLineEdit:hover { border-color: %2; }
        
        QComboBox::drop-down { subcontrol-origin: padding; subcontrol-position: top right; width: 25px; border-top-right-radius: 4px; border-bottom-right-radius: 4px; background-color: %9; border-left-width: 1px; border-left-color: %3; border-left-style: solid; }
        QComboBox::drop-down:hover { background-color: %10; }
        QComboBox::down-arrow { image: none; width: 0px; height: 0px; border: none; }
        QComboBox QAbstractItemView { border: 1px solid %2; selection-background-color: %2; background-color: %7; outline: none; }
        
        /* Start button (green) / 启动按钮 (绿色) */
        QPushButton#btnStart { background-color: #388E3C; color: white; border: 1px solid #2E7D32; }
        QPushButton#btnStart:hover { background-color: #4CAF50; border-color: #43A047; }
        QPushButton#btnStart:pressed { background-color: #1B5E20; border-color: #1B5E20; }
        QPushButton#btnStart:disabled { background-color: transparent; border: 1px solid %1; color: gray; }

        /* Reload button (blue - dynamically set) / 重载按钮 (蓝色 - 动态设置) */
        QPushButton#btnReload { background-color: #0078D4; color: white; border: 1px solid #005A9E; }
        QPushButton#btnReload:hover { background-color: #2B88D8; border-color: #005A9E; }
        QPushButton#btnReload:pressed { background-color: #004578; border-color: #004578; }

        QLabel#lblTokens { color: #E6B422; font-weight: bold; }
        QToolTip { border: 1px solid %2; background-color: %7; color: #E6B422; opacity: 230; padding: 4px; border-radius: 3px; }
    )")
    .arg(qssBtnBorder).arg(highlightColor.name()).arg(qssBtnBorder).arg(qssBtnBg).arg(qssBtnHover)
    .arg(highlightColor.name()).arg(baseColor.name()).arg(textColor.name()).arg(dropDownBg).arg(dropDownHover);
    
    qApp->setStyleSheet(qss);
    m_isDarkTheme = isDark;
}

void MainWindow::setupUi() {
    // Create central widget / 创建中心部件
    QWidget *central = new QWidget(this);
    setCentralWidget(central);
    QVBoxLayout *mainLayout = new QVBoxLayout(central);
    mainLayout->setSpacing(10);
    mainLayout->setContentsMargins(10, 10, 10, 10);

    // API Configuration Group / API配置分组
    cfgGroup = new QGroupBox(this);
    QGridLayout *grid = new QGridLayout(cfgGroup);
    grid->setColumnStretch(1, 1);
    grid->setVerticalSpacing(8);
    grid->setHorizontalSpacing(10);

    // Lambda function for creating aligned labels / 用于创建对齐标签的Lambda函数
    auto createLabel = [this](QLabel*& memberPtr) {
        memberPtr = new QLabel(this);
        memberPtr->setAlignment(Qt::AlignRight | Qt::AlignVCenter);
        return memberPtr;
    };

    // API Address ComboBox / API地址组合框
    apiAddressCombo = new QComboBox(this);
    apiAddressCombo->setEditable(true); 
    apiAddressCombo->setMinimumHeight(28);
    for(const auto& p : PRESETS_DATA) {
        apiAddressCombo->addItem(p.url);
        apiAddressCombo->setItemData(apiAddressCombo->count()-1, p.tips[m_currentLang], Qt::ToolTipRole);
    }
    apiAddressCombo->setCurrentIndex(0);

    grid->addWidget(createLabel(lblApiAddr), 0, 0);
    grid->addWidget(apiAddressCombo, 0, 1);

    // API Key LineEdit / API密钥行编辑框
    apiKeyEdit = new QLineEdit(this);
    apiKeyEdit->setEchoMode(QLineEdit::Normal); 
    grid->addWidget(createLabel(lblApiKey), 1, 0);
    grid->addWidget(apiKeyEdit, 1, 1);

    // Model selection with fetch button / 模型选择带获取按钮
    QWidget *modelContainer = new QWidget(this);
    QHBoxLayout *modelLayout = new QHBoxLayout(modelContainer);
    modelLayout->setContentsMargins(0, 0, 0, 0);
    modelLayout->setSpacing(5);
    
    modelCombo = new QComboBox(this);
    modelCombo->setEditable(true);
    modelCombo->setMinimumHeight(28); 
    
    fetchModelBtn = new QPushButton(this);
    connect(fetchModelBtn, &QPushButton::clicked, this, &MainWindow::onFetchModels);
    
    modelLayout->addWidget(modelCombo, 1); 
    modelLayout->addWidget(fetchModelBtn);
    grid->addWidget(createLabel(lblModel), 2, 0);
    grid->addWidget(modelContainer, 2, 1);

    // Server parameters row / 服务器参数行
    QWidget *paramContainer = new QWidget(this);
    QHBoxLayout *paramLayout = new QHBoxLayout(paramContainer);
    paramLayout->setContentsMargins(0, 0, 0, 0);
    paramLayout->setSpacing(8); 

    lblPort = new QLabel(this);
    portEdit = new QLineEdit(this);
    portEdit->setFixedWidth(55);
    portEdit->setAlignment(Qt::AlignCenter);

    lblThread = new QLabel(this);
    threadSpin = new QSpinBox(this);
    threadSpin->setRange(1, 200);
    threadSpin->setFixedWidth(55);
    threadSpin->setAlignment(Qt::AlignCenter);

    lblTemp = new QLabel(this);
    tempSpin = new QDoubleSpinBox(this);
    tempSpin->setRange(0, 2);
    tempSpin->setSingleStep(0.1);
    tempSpin->setFixedWidth(55);
    tempSpin->setAlignment(Qt::AlignCenter);

    lblCtx = new QLabel(this);
    contextSpin = new QSpinBox(this);
    contextSpin->setRange(0, 20);
    contextSpin->setFixedWidth(55);
    contextSpin->setAlignment(Qt::AlignCenter);

    clearCtxBtn = new QPushButton(this);
    clearCtxBtn->setFixedWidth(50);
    connect(clearCtxBtn, &QPushButton::clicked, this, &MainWindow::onClearContext);

    lblTokens = new QLabel(this);
    lblTokens->setObjectName("lblTokens"); 

    paramLayout->addWidget(lblPort);
    paramLayout->addWidget(portEdit);
    paramLayout->addWidget(lblThread);
    paramLayout->addWidget(threadSpin);
    paramLayout->addWidget(lblTemp);
    paramLayout->addWidget(tempSpin);
    paramLayout->addWidget(lblCtx);
    paramLayout->addWidget(contextSpin);
    paramLayout->addWidget(clearCtxBtn);
    paramLayout->addWidget(lblTokens);
    paramLayout->addStretch();

    grid->addWidget(paramContainer, 3, 0, 1, 2);

    // System Prompt TextEdit / 系统提示词文本编辑框
    systemPromptEdit = new QTextEdit(this);
    systemPromptEdit->setMinimumHeight(100); 

    // System Prompt Label with Lock Checkbox / 系统提示词标签带锁定复选框
    QWidget *sysLabelContainer = new QWidget(this);
    QVBoxLayout *sysLabelLayout = new QVBoxLayout(sysLabelContainer);
    sysLabelLayout->setContentsMargins(0, 0, 0, 0);
    sysLabelLayout->setSpacing(2); 

    lblSysPrompt = new QLabel(this);
    lblSysPrompt->setAlignment(Qt::AlignRight | Qt::AlignTop);

    chkLockSysPrompt = new QCheckBox(this);
    chkLockSysPrompt->setLayoutDirection(Qt::RightToLeft); 

    QWidget *lockContainer = new QWidget(this);
    QHBoxLayout *lockLayout = new QHBoxLayout(lockContainer);
    lockLayout->setContentsMargins(0,0,0,0);
    lockLayout->addStretch(); 
    lockLayout->addWidget(chkLockSysPrompt);

    sysLabelLayout->addWidget(lblSysPrompt);
    sysLabelLayout->addWidget(lockContainer);
    sysLabelLayout->addStretch(); 

    grid->addWidget(sysLabelContainer, 4, 0);
    grid->addWidget(systemPromptEdit, 4, 1);

    // Pre-Prompt LineEdit / 前置文本行编辑框
    prePromptEdit = new QLineEdit(this);
    grid->addWidget(createLabel(lblPrePrompt), 5, 0);
    grid->addWidget(prePromptEdit, 5, 1);

    // 🔥 Layout Fix for Glossary Path Overflow (from 1.txt) / 术语表路径溢出的布局修复（来自1.txt）
    
    // 🔥 CAN: 组装右侧内容容器
    QWidget *glossaryContainer = new QWidget(this);
    QHBoxLayout *glossaryLayout = new QHBoxLayout(glossaryContainer); // 必须创建布局
    glossaryLayout->setContentsMargins(0, 0, 0, 0);

    chkGlossary = new QCheckBox(this);
    
    glossaryCombo = new QComboBox(this);
    glossaryCombo->setEditable(true); 

    // 🔥 CAN: 启用自定义上下文菜单策略
    glossaryCombo->setContextMenuPolicy(Qt::CustomContextMenu);
    // 连接右键点击信号
    connect(glossaryCombo, &QComboBox::customContextMenuRequested, this, &MainWindow::onGlossaryContextMenu);

    glossaryCombo->setMinimumHeight(28);
    // CRITICAL: Prevent long paths from stretching window width / 关键：防止长路径拉伸窗口宽度
    glossaryCombo->setMinimumWidth(0);
    glossaryCombo->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Fixed); 
    
    btnOpenAuto = new QPushButton(STR_BTN_AUTO[m_currentLang], this);
    btnOpenAuto->setFixedWidth(50);
    connect(btnOpenAuto, &QPushButton::clicked, this, &MainWindow::onOpenAutoTranslations);

    btnSelectGlossary = new QPushButton("...", this);
    btnSelectGlossary->setFixedWidth(35);
    connect(btnSelectGlossary, &QPushButton::clicked, this, &MainWindow::onSelectGlossary);

    // 组装右侧
    glossaryLayout->addWidget(chkGlossary);
    glossaryLayout->addWidget(glossaryCombo, 1); // Stretch factor 1 / 拉伸因子1
    glossaryLayout->addWidget(btnOpenAuto);
    glossaryLayout->addWidget(btnSelectGlossary);

    // 🔥 CAN: 组装左侧标签+锁定框
    QWidget *glossaryLabelContainer = new QWidget(this);
    QVBoxLayout *glossaryLabelLayout = new QVBoxLayout(glossaryLabelContainer);
    glossaryLabelLayout->setContentsMargins(0, 0, 0, 0);
    glossaryLabelLayout->setSpacing(2); 

    lblGlossary = new QLabel(this);
    lblGlossary->setAlignment(Qt::AlignRight | Qt::AlignTop);

    chkLockGlossary = new QCheckBox(this);
    chkLockGlossary->setLayoutDirection(Qt::RightToLeft); 

    QWidget *gLockContainer = new QWidget(this);
    QHBoxLayout *gLockLayout = new QHBoxLayout(gLockContainer);
    gLockLayout->setContentsMargins(0, 0, 0, 0);
    gLockLayout->addStretch(); 
    gLockLayout->addWidget(chkLockGlossary);

    glossaryLabelLayout->addWidget(lblGlossary);
    glossaryLabelLayout->addWidget(gLockContainer);
    glossaryLabelLayout->addStretch(); 
    
    grid->addWidget(glossaryLabelContainer, 6, 0); // 放在第6行第0列
    grid->addWidget(glossaryContainer, 6, 1); // 放在第6行第1列

    mainLayout->addWidget(cfgGroup);

    // Control buttons grid / 控制按钮网格
    QGridLayout *btnGridLayout = new QGridLayout();
    btnGridLayout->setSpacing(10);
    
    auto createBtn = [this] (QPushButton*& btnPtr) {
        btnPtr = new QPushButton(this);
        btnPtr->setMinimumHeight(32);
        btnPtr->setCursor(Qt::PointingHandCursor);
        return btnPtr;
    };

    btnGridLayout->addWidget(createBtn(startBtn), 0, 0);
    startBtn->setObjectName("btnStart"); 

    btnGridLayout->addWidget(createBtn(stopBtn), 0, 1);
    stopBtn->setEnabled(false);
    
    hudBtn = new QPushButton(this);
    hudBtn->setMinimumHeight(32);
    hudBtn->setCursor(Qt::PointingHandCursor);
    hudBtn->setEnabled(false); 
    connect(hudBtn, &QPushButton::clicked, this, &MainWindow::switchToHud);
    btnGridLayout->addWidget(hudBtn, 0, 2);

    btnGridLayout->addWidget(createBtn(testBtn), 1, 0);
    btnGridLayout->addWidget(createBtn(exportBtn), 1, 1);
    btnGridLayout->addWidget(createBtn(loadBtn), 1, 2);

    btnGridLayout->addWidget(createBtn(saveBtn), 2, 0);
    btnGridLayout->addWidget(createBtn(themeBtn), 2, 1);
    btnGridLayout->addWidget(createBtn(langBtn), 2, 2);

    // Connect button signals / 连接按钮信号
    connect(themeBtn, &QPushButton::clicked, this, &MainWindow::toggleTheme);
    connect(langBtn, &QPushButton::clicked, this, &MainWindow::toggleLanguage);
    connect(startBtn, &QPushButton::clicked, this, &MainWindow::onStartClicked);
    connect(stopBtn, &QPushButton::clicked, this, &MainWindow::onStopClicked);
    connect(testBtn, &QPushButton::clicked, this, &MainWindow::onTestConfig);
    connect(loadBtn, &QPushButton::clicked, this, &MainWindow::onLoadConfig);
    connect(saveBtn, &QPushButton::clicked, this, &MainWindow::onSaveConfig);
    connect(exportBtn, &QPushButton::clicked, this, &MainWindow::onExportLog);

    mainLayout->addLayout(btnGridLayout);

    // Log area / 日志区域
    logGroup = new QGroupBox(this);
    QVBoxLayout *logLayout = new QVBoxLayout(logGroup);
    logLayout->setContentsMargins(10, 20, 10, 10);
    logArea = new QTextEdit(this);
    logArea->setReadOnly(true);
    logArea->setMinimumHeight(150); 
    logArea->setContextMenuPolicy(Qt::CustomContextMenu);
    connect(logArea, &QTextEdit::customContextMenuRequested, this, &MainWindow::onLogContextMenu);
    logLayout->addWidget(logArea);
    mainLayout->addWidget(logGroup);

    // Create loading overlay for fetch button / 为获取按钮创建加载覆盖层
    fetchLoadingOverlay = new LoadingOverlay(fetchModelBtn);

    // Connect glossary combo box signal / 连接术语表组合框信号
    connect(glossaryCombo, &QComboBox::activated, this, &MainWindow::onGlossaryChanged);

    connect(glossaryCombo, QOverload<int>::of(&QComboBox::currentIndexChanged), [this](int index){
    Q_UNUSED(index);
    // 使用 QTimer::singleShot 是为了确保在 Qt 完成内部文本渲染后再执行光标移动
    QTimer::singleShot(0, [this](){
        if (glossaryCombo->lineEdit()) {
            glossaryCombo->lineEdit()->setCursorPosition(0);
        }
    });
    });

}

void MainWindow::onLogContextMenu(const QPoint &pos) {
    // Create standard context menu for text edit / 为文本编辑框创建标准上下文菜单
    QMenu *menu = logArea->createStandardContextMenu();
    menu->addSeparator();
    
    // Add "Clear Log" action / 添加"清空日志"操作
    QAction *clearAction = menu->addAction(STR_CLEAR_LOG[m_currentLang]);
    connect(clearAction, &QAction::triggered, logArea, &QTextEdit::clear);
    
    // Show menu at cursor position / 在光标位置显示菜单
    menu->exec(logArea->mapToGlobal(pos));
    delete menu;
}

void MainWindow::loadConfigToUi() {
    // Load configuration from file / 从文件加载配置 (Manager 依然负责基础数据)
    AppConfig cfg = ConfigManager::loadConfig();
    
    // 1. 🔥 CAN: 独立恢复锁定框状态 (不经过结构体)
    // 直接从 config.ini 读取锁定状态。如果没有该值，默认为 false。
    QSettings sess("config.ini", QSettings::IniFormat);
    bool isLocked = sess.value("Settings/lock_glossary_path", false).toBool();
    chkLockGlossary->setChecked(isLocked);

    // 2. 填充常规 UI 元素
    apiAddressCombo->setCurrentText(cfg.api_address);
    apiKeyEdit->setText(cfg.api_key);
    modelCombo->setCurrentText(cfg.model_name);
    portEdit->setText(QString::number(cfg.port));
    tempSpin->setValue(cfg.temperature);
    contextSpin->setValue(cfg.context_num);
    threadSpin->setValue(cfg.max_threads);
    systemPromptEdit->setText(cfg.system_prompt);
    prePromptEdit->setText(cfg.pre_prompt);
    chkGlossary->setChecked(cfg.enable_glossary);

    // 3. 加载术语表历史记录
    glossaryCombo->clear();
    if (!cfg.glossary_history.isEmpty()) {
        glossaryCombo->addItems(cfg.glossary_history);
    }
    
    // 4. 设置当前术语表路径
    if (!cfg.glossary_path.isEmpty()) {
        int index = glossaryCombo->findText(cfg.glossary_path);
        if (index != -1) glossaryCombo->setCurrentIndex(index);
        else addToGlossaryHistory(cfg.glossary_path);
    }
    
    // -------------------------------------------------------------
    // ✅ 启动时强制光标聚焦到路径开头 (Focus Forward)
    // -------------------------------------------------------------
    if (glossaryCombo->lineEdit()) {
        glossaryCombo->lineEdit()->setCursorPosition(0);
    }
    
    // 设置语言
    m_currentLang = cfg.language;
}

AppConfig MainWindow::getUiConfig() {
    // Collect current UI state into config object / 将当前UI状态收集到配置对象中
    AppConfig cfg;
    cfg.api_address = apiAddressCombo->currentText();
    cfg.api_key = apiKeyEdit->text();
    cfg.model_name = modelCombo->currentText();
    cfg.port = portEdit->text().toInt();
    cfg.temperature = tempSpin->value();
    cfg.context_num = contextSpin->value();
    cfg.max_threads = threadSpin->value();
    cfg.system_prompt = systemPromptEdit->toPlainText();
    cfg.pre_prompt = prePromptEdit->text();
    cfg.enable_glossary = chkGlossary->isChecked();
    
    // 🔥 CAN: 剥离 lock_glossary_path (不再赋值给 cfg)
    // 这里只收集结构体定义的字段。锁定框的状态我们会在 closeEvent 里单独存。
    
    cfg.glossary_path = glossaryCombo->currentText();
    
    // 保存术语表历史记录
    QStringList history;
    for(int i = 0; i < glossaryCombo->count(); ++i) {
        history << glossaryCombo->itemText(i);
    }
    cfg.glossary_history = history;
    cfg.language = m_currentLang;
    
    return cfg;
}

void MainWindow::toggleControls(bool running) {
    m_isServerRunning = running;

    // --- ✅ 关键修改：解除锁定以支持热重载 ---
    // 允许在运行时修改 API 地址、密钥、模型和参数
    apiAddressCombo->setEnabled(true); 
    apiKeyEdit->setEnabled(true);
    modelCombo->setEnabled(true);      // 确保模型选择框也保持开启
    tempSpin->setEnabled(true);        // 允许运行时调整温度
    contextSpin->setEnabled(true);     // 允许运行时调整上下文记忆

    // 只有端口和线程数建议保持锁定 (修改这些通常需要彻底重启 Socket 或线程池)
    portEdit->setEnabled(!running);
    threadSpin->setEnabled(!running);
    
    // 2. 术语表逻辑 (UNFROZEN: 保持第一份代码的灵活性)
    glossaryCombo->setEnabled(true); 

    // 3. 🔥 HUD 按钮修复: 只在启动服务后才可使用
    hudBtn->setEnabled(running);

    // 4. 省略号按钮交互 (保留第一份代码的高级视觉反馈)
    QString baseDescription = (m_currentLang == 0) 
        ? "Select glossary files (.txt)" 
        : "选择术语表文件 (.txt)";

    if (running) {
        // 追加运行状态提示
        QString runningNotice = (m_currentLang == 0)
            ? "\n\n(ℹ️ Server is running: You can still click to change paths \n\n You can right-click on the glossary path to open the clean menu)"
            : "\n\n(ℹ️ 服务运行中：您仍可点击此处更改路径 \n\n 您可以在术语表路径上右键以打开清理菜单)";
        btnSelectGlossary->setToolTip(baseDescription + runningNotice);

        // 样式：平时低调，悬浮点亮
        btnSelectGlossary->setStyleSheet(
            "QPushButton { "
            "  color: rgba(200, 200, 200, 120); " 
            "  border: 1px solid rgba(150, 150, 150, 60); "
            "  background-color: transparent; "
            "} "
            "QPushButton:hover { "
            "  color: #ffffff; "
            "  background-color: #3d8af7; "
            "  border: 1px solid #3d8af7; "
            "}"
        );
    } else {
        btnSelectGlossary->setToolTip(baseDescription);
        btnSelectGlossary->setStyleSheet(""); 
    }

    // 5. 功能性按钮保持可用
    themeBtn->setEnabled(true);
    langBtn->setEnabled(true);
    clearCtxBtn->setEnabled(true); // 运行时允许手动清空记忆

    // 6. 服务控制按钮切换与样式刷新
    if (running) {
        startBtn->setText(m_currentLang == 0 ? "Reload Config" : "重载配置");
        startBtn->setObjectName("btnReload"); // 应用热重载蓝色样式
    } else {
        startBtn->setText(m_currentLang == 0 ? "Start Server" : "启动服务");
        startBtn->setObjectName("btnStart");  // 恢复启动绿色样式
    }
    stopBtn->setEnabled(running);

    // 🔥 必须执行样式重刷，否则 ObjectName 的改变不会立即触发 CSS 颜色变化
    startBtn->style()->unpolish(startBtn);
    startBtn->style()->polish(startBtn);
}

// 🔥 CRITICAL: Robust Hot Reload Logic from 1.txt / 关键：来自1.txt的鲁棒热重载逻辑
void MainWindow::onStartClicked() {
    AppConfig newCfg = getUiConfig();

    if (m_isServerRunning) {
        // === 🔥 完整热重载逻辑 (Hot Reload) ===
        AppConfig oldCfg = server->getConfig();
        
        // 1. 模型切换检测记录
        if (oldCfg.model_name != newCfg.model_name) {
            onLogMessage(QString(LOG_MODEL_SWITCH[m_currentLang])
                            .arg(oldCfg.model_name)
                            .arg(newCfg.model_name));
        } else {
            onLogMessage(QString(LOG_MODEL_SAME[m_currentLang]).arg(newCfg.model_name));
        }

        // 2. 更新服务器配置
        server->updateConfig(newCfg);

        

        onLogMessage(LOG_RELOADED[m_currentLang]);
        
        // 3. 视觉反馈：按钮闪烁动画 (从原始版本恢复)
        QPropertyAnimation *anim = new QPropertyAnimation(startBtn, "windowOpacity");
        anim->setDuration(150);
        anim->setStartValue(0.5);
        anim->setEndValue(1.0);
        anim->start(QAbstractAnimation::DeleteWhenStopped);

        // 4. 自动测试连通性
        onLogMessage(LOG_AUTO_TESTING[m_currentLang]);
        onTestConfig();

    } else {
        // === 🚀 正常启动逻辑 (Start) ===
        server->updateConfig(newCfg);
        server->startServer();
        toggleControls(true); 
    }
}

void MainWindow::onStopClicked() {
    server->stopServer();
    toggleControls(false); 
}

void MainWindow::onLogMessage(QString msg) {
    // Append message to log area / 将消息追加到日志区域
    logArea->append(msg);
    
    // Limit log size to prevent memory issues / 限制日志大小以防止内存问题
    const int MAX_LOG_LINES = 2000;
    if (logArea->document()->blockCount() > MAX_LOG_LINES) {
        QTextCursor cursor(logArea->document());
        cursor.movePosition(QTextCursor::Start);
        for(int i = 0; i < 500; ++i) {
            cursor.movePosition(QTextCursor::NextBlock, QTextCursor::KeepAnchor);
        }
        cursor.removeSelectedText();
    }
}

void MainWindow::onSaveConfig() {
    // Open save file dialog / 打开保存文件对话框
    QString fileName = QFileDialog::getSaveFileName(this, STR_SAVE[m_currentLang], "config.ini", "Config Files (*.ini)");
    if (!fileName.isEmpty()) {
        ConfigManager::saveConfig(getUiConfig(), fileName);
        logArea->append(QString(LOG_CFG_SAVED[m_currentLang]) + fileName);
    }
}

void MainWindow::onLoadConfig() {
    // Open load file dialog / 打开加载文件对话框
    QString fileName = QFileDialog::getOpenFileName(this, STR_LOAD[m_currentLang], "", "Config Files (*.ini)");
    if (fileName.isEmpty()) return;

    // 1. 从文件加载配置（Manager 依然只负责它能读到的基础数据）
    AppConfig cfg = ConfigManager::loadConfig(fileName);
    
    // 2. 更新基础 UI 元素
    apiAddressCombo->setCurrentText(cfg.api_address);
    apiKeyEdit->setText(cfg.api_key);
    modelCombo->setCurrentText(cfg.model_name);
    portEdit->setText(QString::number(cfg.port));
    tempSpin->setValue(cfg.temperature);
    contextSpin->setValue(cfg.context_num);
    threadSpin->setValue(cfg.max_threads);
    
    // 系统提示词锁定逻辑
    if (!chkLockSysPrompt->isChecked()) {
        systemPromptEdit->setText(cfg.system_prompt);
    }

    prePromptEdit->setText(cfg.pre_prompt);
    chkGlossary->setChecked(cfg.enable_glossary);

    // -------------------------------------------------------------
    // 🔥 CAN: 冻结方法实现 (The Freeze Method)
    // -------------------------------------------------------------
    // 只有在当前【锁定框未勾选】的情况下，才允许从配置文件更新术语表环境。
    // 如果已锁定，下面整个代码块将被跳过，实现术语表路径和历史记录的“瞬间冻结”。
    if (!chkLockGlossary->isChecked()) {
        // A. 更新历史记录列表
        if (!cfg.glossary_history.isEmpty()) {
            glossaryCombo->clear();
            glossaryCombo->addItems(cfg.glossary_history);
        }
        
        // B. 更新当前显示的路径
        if (!cfg.glossary_path.isEmpty()) {
            glossaryCombo->setCurrentText(cfg.glossary_path);
        }

        // 注意：这里不再从 cfg 读取 lock_glossary_path，
        // 因为我们已经解耦了它。锁定状态由 UI 当前状态决定。
    }

    // -------------------------------------------------------------
    // ✅ 保持强制焦点前移
    // 确保无论是否更新了路径，显示的一直是路径的开头
    // -------------------------------------------------------------
    if (glossaryCombo->lineEdit()) {
        glossaryCombo->lineEdit()->setCursorPosition(0);
    }
    
    logArea->append(QString(LOG_CFG_LOADED[m_currentLang]) + fileName);
}

void MainWindow::onExportLog() {
    // Export log to file / 将日志导出到文件
    QString fileName = "run_log.txt";
    QFile file(fileName);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&file);
        #if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
            out.setEncoding(QStringConverter::Utf8);
        #else
            out.setCodec("UTF-8");
        #endif
        out << logArea->toPlainText();
        logArea->append(LOG_EXPORTED[m_currentLang]);
    }
}

void MainWindow::onFetchModels() {
    // Get API address from combo box / 从组合框获取API地址
    QString url = apiAddressCombo->currentText();
    if(url.isEmpty()) return;
    if(url.endsWith("/")) url.chop(1);
    
    // Show loading overlay / 显示加载覆盖层
    if(fetchLoadingOverlay) {
        fetchLoadingOverlay->setGeometry(fetchModelBtn->rect());
        fetchLoadingOverlay->raise();
        fetchLoadingOverlay->start();
    }

    logArea->append(m_currentLang == 1 ? "🔍 正在获取模型列表..." : "🔍 Fetching models...");
    
    // Create network request / 创建网络请求
    QNetworkAccessManager *mgr = new QNetworkAccessManager(this);
    QNetworkRequest req(url + "/models");
    req.setTransferTimeout(10000); // 10 second timeout / 10秒超时
    
    // Get first API key from comma-separated list / 从逗号分隔的列表中获取第一个API密钥
    QString key = apiKeyEdit->text().split(',')[0].trimmed();
    req.setRawHeader("Authorization", ("Bearer " + key).toUtf8());
    
    QNetworkReply *reply = mgr->get(req);
    connect(reply, &QNetworkReply::finished, [this, reply, mgr](){
        // Hide loading overlay / 隐藏加载覆盖层
        if(fetchLoadingOverlay) fetchLoadingOverlay->stop();

        if(reply->error() == QNetworkReply::NoError) {
            try {
                // Parse JSON response / 解析JSON响应
                auto jsonDoc = nlohmann::json::parse(reply->readAll().toStdString());
                modelCombo->clear();
                int count = 0;
                for(const auto& item : jsonDoc["data"]) {
                    modelCombo->addItem(QString::fromStdString(item["id"]));
                    count++;
                }
                logArea->append(m_currentLang == 1 ? QString("✅ 获取成功！共发现 %1 个可用模型。").arg(count) 
                                                 : QString("✅ Success! Found %1 available models.").arg(count));
                modelCombo->setFocus();
            } catch(...) {
                logArea->append("❌ " + QString(LOG_PARSE_ERR[m_currentLang]));
            }
        } else {
            // Handle error / 处理错误
            int statusCode = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
            if (reply->error() == QNetworkReply::TimeoutError) statusCode = 999;
            logArea->append("❌ " + getFriendlyErrorMessage(statusCode, m_currentLang));
        }
        reply->deleteLater();
        mgr->deleteLater();
    });
}

void MainWindow::onTestConfig() {
    logArea->append(LOG_TEST_START[m_currentLang]);
    
    // Get API keys from comma-separated list / 从逗号分隔的列表中获取API密钥
    QStringList keys = apiKeyEdit->text().split(',', Qt::SkipEmptyParts);
    if (keys.isEmpty()) {
        logArea->append(LOG_NO_KEY[m_currentLang]);
        return;
    }
    
    testBtn->setEnabled(false);
    
    // Prepare API endpoint URL / 准备API端点URL
    QString url = apiAddressCombo->currentText();
    if(url.endsWith("/")) url.chop(1);
    url += "/chat/completions";
    QString model = modelCombo->currentText();

    // Shared counters for tracking completion / 用于跟踪完成的共享计数器
    auto finishedCount = std::make_shared<int>(0);
    auto successCount = std::make_shared<int>(0);
    int total = keys.size();

    // Test each API key / 测试每个API密钥
    for (int i = 0; i < total; ++i) {
        QString key = keys[i].trimmed();
        // 💡 Restore previous masking logic: (... + last 8 digits) / 还原之前的脱敏逻辑：(... + 后8位)
        QString keyMasked = (key.length() > 8) ? ("..." + key.right(8)) : key;
        
        QNetworkAccessManager *mgr = new QNetworkAccessManager(this);
        QNetworkRequest req(url);
        req.setTransferTimeout(10000); // 10 second timeout / 10秒超时
        
        req.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
        req.setRawHeader("Authorization", ("Bearer " + key).toUtf8());
        
        // Prepare test request JSON / 准备测试请求JSON
        nlohmann::json j;
        j["model"] = model.toStdString();
        j["messages"] = nlohmann::json::array({{{"role", "user"}, {"content", "Hi"}}});
        j["max_tokens"] = 5;
        
        QNetworkReply *reply = mgr->post(req, QByteArray::fromStdString(j.dump()));
        
        // 💡 Capture [=] to ensure correct copy of i / 捕获 [=] 以确保 i 副本正确
        connect(reply, &QNetworkReply::finished, [this, reply, mgr, keyMasked, i, finishedCount, successCount, total](){
            (*finishedCount)++;
            bool isOk = (reply->error() == QNetworkReply::NoError);
            if(isOk) (*successCount)++;

            int statusCode = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
            if (reply->error() == QNetworkReply::TimeoutError) statusCode = 999;

            // 💡 Construct classic output line / 构造经典输出行
            QString icon = isOk ? "✅" : "❌";
            QString status = isOk ? (m_currentLang == 1 ? "测试通过" : "PASS") 
                                 : getFriendlyErrorMessage(statusCode, m_currentLang);
            
            // Format: ✅ Key-1 (...SEPO): 测试通过 / 格式：✅ Key-1 (...SEPO): 测试通过
            logArea->append(QString("%1 Key-%2 (%3): %4")
                            .arg(icon).arg(i + 1).arg(keyMasked).arg(status));

            // 💡 Summary prompt / 汇总提示
            if (*finishedCount == total) {
                testBtn->setEnabled(true);
                logArea->append("----------------------------------");
                QString summary = (m_currentLang == 1) 
                    ? QString("📊 测试结束！成功: %1, 失败: %2").arg(*successCount).arg(total - *successCount)
                    : QString("📊 Finished! Success: %1, Failed: %2").arg(*successCount).arg(total - *successCount);
                logArea->append("<b>" + summary + "</b>");
            }

            reply->deleteLater();
            mgr->deleteLater();
        });
    }
}

void MainWindow::updateTokenDisplay(long long total, long long prompt, long long completion) {
    // 1. Store values in widget properties (Qt dynamic properties, no need to define variables in .h)
    // 1. 将数值存入控件属性中 (Qt 动态属性，不需要在 .h 中定义变量)
    lblTokens->setProperty("total", total);
    lblTokens->setProperty("prompt", prompt);
    lblTokens->setProperty("completion", completion);

    // 2. Update main interface text / 2. 更新主界面文字
    lblTokens->setText(QString("%1 %2").arg(STR_TOKENS[m_currentLang]).arg(total));

    // 3. Combine tooltip: description + detailed data (fix "splitting" issue) / 3. 组合提示：说明文字 + 详细数据 (修正"分裂"问题)
    QString strPrompt = (m_currentLang == 1) ? "输入 (Prompt):" : "Input (Prompt):";
    QString strCompletion = (m_currentLang == 1) ? "输出 (Completion):" : "Output (Completion):";

    QString fullTip = QString("<b>%1</b><br><br>%2 %3<br>%4 %5")
                        .arg(TIP_TOKENS[m_currentLang])
                        .arg(strPrompt).arg(prompt)
                        .arg(strCompletion).arg(completion);

    lblTokens->setToolTip(fullTip);
}

void MainWindow::onClearContext() {
    server->clearAllContexts();
}

void MainWindow::switchToHud() {
    if (!server) return;
    
    // Fade out animation / 淡出动画
    QPropertyAnimation *anim = new QPropertyAnimation(this, "windowOpacity");
    anim->setDuration(300);
    anim->setStartValue(1.0);
    anim->setEndValue(0.0);
    
    connect(anim, &QPropertyAnimation::finished, [this](){
        this->hide();
        // Position HUD window near main window / 将HUD窗口定位在主窗口附近
        m_hudWindow->move(this->geometry().topRight() - QPoint(280, -20)); 
        m_hudWindow->show();
        m_hudWindow->setStatus(false);
        m_hudWindow->updateTokens(m_tokenManager->getTotal());
    });
    anim->start(QAbstractAnimation::DeleteWhenStopped);
}

void MainWindow::restoreFromHud() {
    m_hudWindow->hide();
    this->setWindowOpacity(0.0);
    this->show();
    
    // Fade in animation / 淡入动画
    QPropertyAnimation *anim = new QPropertyAnimation(this, "windowOpacity");
    anim->setDuration(300);
    anim->setStartValue(0.0);
    anim->setEndValue(1.0);
    anim->start(QAbstractAnimation::DeleteWhenStopped);
}

void MainWindow::onServerWorkStarted() {
    if (m_hudWindow && m_hudWindow->isVisible()) {
        m_hudWindow->setStatus(true);
    }
}

void MainWindow::onServerWorkFinished(bool success) {
    if (m_hudWindow && m_hudWindow->isVisible()) {
        m_hudWindow->setStatus(false, !success); 
    }
}

// Glossary Mangagement Context Menu Handler / 术语表管理右键菜单处理器

void MainWindow::onGlossaryContextMenu(const QPoint &pos) {
    int lang = m_currentLang;
    
    // 创建右键菜单
    QMenu menu(this);
    
    // 动作 1：删除当前选中的这一条
    QAction *removeAction = menu.addAction(STR_REMOVE_PATH[lang]);
    // 动作 2：清空全部
    QAction *clearAction = menu.addAction(STR_CLEAR_HISTORY[lang]);
    
    // 如果当前是空的，禁用删除动作
    if (glossaryCombo->currentText().isEmpty()) {
        removeAction->setEnabled(false);
    }

    // 在鼠标位置弹出菜单
    QAction *selectedAction = menu.exec(glossaryCombo->mapToGlobal(pos));
    
    if (selectedAction == removeAction) {
        // --- 逻辑：删除当前项 ---
        int index = glossaryCombo->currentIndex();
        if (index != -1) {
            glossaryCombo->removeItem(index);
            logArea->append(lang == 1 ? "🧽 已从历史记录中移除该路径。" : "🧽 Removed current path from history.");
        } else {
            // 如果是用户刚输入但没进列表的文字，直接清空输入框
            glossaryCombo->setEditText("");
        }
    } else if (selectedAction == clearAction) {
        // --- 逻辑：清空全部 ---
        glossaryCombo->clear();
        logArea->append(lang == 1 ? "🗑️ 术语表历史记录已清空。" : "🗑️ Glossary history cleared.");
    }
}

// 🛠️ Human-friendly error message mapping / 人性化错误信息映射
// Added at the end of MainWindow.cpp / 在 MainWindow.cpp 的末尾添加：

QString MainWindow::getFriendlyErrorMessage(int code, int lang) {
    if (lang == 1) { // 简体中文
        switch (code) {
            case 0:   return "网络连接超时: 无法连接到服务器，请检查 API 地址或网络代理。";
            case 400: return "请求格式错误 (400): 请检查参数设置是否符合该模型要求。";
            case 401: return "身份验证失败 (401): API Key 或是 API地址 填写错误、已过期或已被封禁。";
            case 402: return "额度不足 (402): 账户余额已耗尽，请前往官网充值。";
            case 403: return "拒绝访问 (403): 权限不足，或者该 Key 不支持访问所选模型。";
            case 404: return "地址错误 (404): API 地址或路径错误，请检查末尾是否多/少了 /v1。";
            case 429: return "频率限制/额度用尽 (429): 请求太快了，或者本月免费额度已领完。";
            case 500: return "服务器错误 (500): 供应商服务器崩溃了。";
            case 503: return "服务不可用 (503): 供应商正在维护中。";
            case 999: return "连接超时 (10s): 服务器响应太慢，请检查网络是否稳定。";
            default: return QString("网络错误 (%1): 请检查 API 地址是否有效。").arg(code);
        }
    } else { // English
        switch (code) {
            case 0:   return "Connection Timeout: Please check your network or proxy.";
            case 400: return "Bad Request (400): Please check if parameters meet model requirements.";
            case 401: return "Auth Failed (401): Invalid or expired API Key/Address.";
            case 402: return "Insufficient Balance (402): Please top up your account.";
            case 403: return "Forbidden (403): Access denied or Key lacks model permissions.";
            case 429: return "Rate Limit (429): Too many requests or quota exhausted.";
            case 404: return "Not Found (404): Check your API URL.";
            case 500: return "Server Error (500): Provider server crashed.";
            case 503: return "Service Unavailable (503): Provider is under maintenance.";
            case 999: return "Connection Timeout (10s): Server response too slow.";
            default: return QString("Error (%1): Check provider status.").arg(code);
        }
    }
}

void MainWindow::onGlossaryChanged() {
    // 获取当前 UI 状态
    AppConfig currentCfg = getUiConfig(); 
    
    // 如果服务器正在运行，立即同步配置到 Server 实例
    if (m_isServerRunning && server) {
        server->updateConfig(currentCfg);
        
        // 打印反馈日志
        QString msg = (m_currentLang == 0) 
            ? QString("🔄 Glossary switched to: %1").arg(currentCfg.glossary_path)
            : QString("🔄 术语表已切换至: %1").arg(currentCfg.glossary_path);
        onLogMessage(msg);
    }
}
