#pragma once

#include <QMainWindow>
#include <QPointer>

// Include basic widget definitions required by the compiler
// 包含编译器需要的基础控件定义
#include <QLineEdit>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QCheckBox>
#include <QScrollArea>

#include "TranslationServer.h"
#include "TokenManager.h"
#include "ModernUI.h"

/**
 * ModernWindow class – the glass/fluid UI mode main window.
 * ModernWindow 类 – 玻璃/流光模式的主窗口。
 * 
 * This window provides an alternative, visually enhanced interface for the translator.
 * It uses custom widgets like SideGlassCombo and supports dynamic opacity, rounded corners,
 * and a floating glossary editor.
 * 该窗口为翻译器提供了另一种视觉增强的界面。
 * 它使用诸如 SideGlassCombo 等自定义控件，并支持动态透明度、圆角和悬浮术语表编辑器。
 */
class ModernWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * Constructor. Initializes the modern UI and connects signals.
     * 构造函数。初始化流光界面并连接信号。
     * 
     * @param server Pointer to the shared TranslationServer instance.
     * @param parent Parent widget (usually nullptr).
     * @param server 指向共享的 TranslationServer 实例的指针。
     * @param parent 父窗口（通常为nullptr）。
     */
    explicit ModernWindow(TranslationServer *server, QWidget *parent = nullptr);
    
    /**
     * Destructor. Cleans up resources.
     * 析构函数。清理资源。
     */
    ~ModernWindow();

    /**
     * Get the server instance.
     * 获取服务器实例。
     */
    TranslationServer *getServer() const { return m_server; }

    /**
     * Retrieve the current UI state as an AppConfig structure.
     * 获取当前UI状态（以AppConfig结构体形式）。
     */
    AppConfig getUiConfig();

    /**
     * Load configuration from file and update the UI.
     * 从文件加载配置并更新UI。
     */
    void loadConfigToUi();

signals:
    /**
     * Signal emitted when the user requests to switch back to classic mode.
     * 当用户请求切换回经典模式时发射的信号。
     */
    void requestClassicMode();

protected:
    /**
     * Custom paint event to draw the translucent background with optional noise texture.
     * 自定义绘制事件，绘制半透明背景及可选的噪点纹理。
     */
    void paintEvent(QPaintEvent *event) override;

    /**
     * Handle show event to synchronize UI after the window becomes visible.
     * 处理显示事件，在窗口可见后同步UI。
     */
    void showEvent(QShowEvent *event) override;

    /**
     * Handle close event to save configuration and perform fade‑out.
     * 处理关闭事件，保存配置并执行淡出。
     */
    void closeEvent(QCloseEvent *event) override;

    // Drag support for the frameless window (avoids accidental interactions)
    // 无边框窗口的拖动支持（防误触）
    void mousePressEvent(QMouseEvent *event) override;
    void mouseMoveEvent(QMouseEvent *event) override;
    void mouseReleaseEvent(QMouseEvent *event) override;

private slots:
    // ========== Basic operations ==========
    void onLoadConfig();                ///< Load configuration from file / 从文件加载配置
    void onSaveConfig();                ///< Save configuration to file / 将配置保存到文件
    void toggleLanguage();              ///< Switch interface language / 切换界面语言
    void toggleTheme();                 ///< Switch between dark and light themes / 切换深色/亮色主题
    void onExportLog();                 ///< Export log to file / 将日志导出到文件
    void onSwitchClicked();             ///< Switch back to classic mode / 切换回经典模式
    void onPowerClicked();              ///< Start or reload server / 启动或重载服务器
    void onStopClicked();               ///< Stop the server / 停止服务器
    void onFetchModels();               ///< Fetch model list from API / 从API获取模型列表
    void onTestConfig();                 ///< Test API keys / 测试API密钥
    void onOpacityChange(int val);       ///< Handle opacity slider change / 处理透明度滑块变化
    void updateLog(QString msg);         ///< Append a message to the log area / 将消息追加到日志区域
    void updateToken(long long total, long long p, long long c); ///< Update token display / 更新令牌显示
    void onClearContext();                ///< Clear all context memory / 清除所有上下文记忆
    void onOpenAutoTranslations();        ///< Open _AutoGeneratedTranslations.txt / 打开自动翻译文件
    void onEditGlossaryClicked();         ///< Open the glossary drawer / 打开术语表抽屉
    void onGlossaryContextMenu(const QPoint &pos); ///< Show context menu for glossary / 显示术语表右键菜单
    void onLogContextMenu(const QPoint &pos);       ///< Show context menu for log area / 显示日志区域右键菜单
    void onGlossaryChanged();              ///< Handle glossary selection change / 处理术语表选择变化
    void onSelectGlossary();               ///< Browse and select a glossary file / 浏览并选择术语表文件
    void toggleShape();                    ///< Toggle between rounded and square corners / 切换圆角/直角
    void toggleDebugMode();                ///< Toggle debug (speed test) mode / 切换测速模式

private:
    /**
     * Set up the user interface (create widgets, layouts, connections).
     * 设置用户界面（创建控件、布局、连接）。
     */
    void setupUi();

    /**
     * Update all UI texts according to the current language.
     * 根据当前语言更新所有界面文本。
     */
    void updateUIText();

    /**
     * Update the power button state (start/reload) based on server running status.
     * 根据服务器运行状态更新电源按钮状态（启动/重载）。
     * 
     * @param running True if server is running.
     */
    void updatePowerButtonState(bool running);

    /**
     * Add a glossary path to the history combo box.
     * 将术语表路径添加到历史组合框。
     * 
     * @param path The file path to add.
     */
    void addToGlossaryHistory(const QString &path);

    /**
     * Return a user‑friendly error message based on HTTP status code.
     * 根据HTTP状态码返回用户友好的错误信息。
     * 
     * @param code HTTP status code.
     * @param lang Language (0=English, 1=Chinese).
     * @return Friendly error string.
     */
    QString getFriendlyErrorMessage(int code, int lang);

    bool m_isRounded = true;           ///< Current corner style (true = rounded) / 当前圆角样式（true=圆角）
    QPushButton *btnShape;              ///< Button to toggle corner shape / 切换圆角的按钮

    /**
     * Reset cursor positions to the start for all editable combo boxes and line edits.
     * 将所有可编辑组合框和行编辑的光标位置重置到开头。
     */
    void resetAllCursors()
    {
        QTimer::singleShot(20, [this]()
                           {
            if (apiAddressCombo && apiAddressCombo->lineEdit()) apiAddressCombo->lineEdit()->setCursorPosition(0);
            if (modelCombo && modelCombo->lineEdit()) modelCombo->lineEdit()->setCursorPosition(0);
            if (glossaryCombo && glossaryCombo->lineEdit()) glossaryCombo->lineEdit()->setCursorPosition(0);
            if (apiKeyEdit) apiKeyEdit->setCursorPosition(0);
            if (prePromptEdit) prePromptEdit->setCursorPosition(0); });
    }

    /**
     * Update environment (theme, opacity, rounded state) for custom combo boxes.
     * 更新自定义组合框的环境参数（主题、透明度、圆角）。
     */
    void updateComboEnv()
    {
        if (apiAddressCombo)
            apiAddressCombo->setEnv(m_isDark, m_alpha, m_isRounded);
        if (modelCombo)
            modelCombo->setEnv(m_isDark, m_alpha, m_isRounded);
        if (glossaryCombo)
            glossaryCombo->setEnv(m_isDark, m_alpha, m_isRounded);
    }

    /**
     * Perform a smooth visual transition when changing UI state.
     * 在更改UI状态时执行平滑视觉过渡。
     * 
     * @param changeLogic The actual UI change to perform.
     */
    void smoothSwitch(std::function<void()> changeLogic);

    // Core objects / 核心对象
    TranslationServer *m_server;        ///< Translation server instance / 翻译服务器实例
    TokenManager *m_tokenManager;       ///< Token usage manager / Token用量管理器

    // UI state / UI状态
    QPoint m_dragPos;                   ///< Drag offset for window movement / 窗口拖拽偏移量
    bool m_isDragging = false;          ///< Flag indicating drag in progress / 拖拽进行中的标志
    int m_alpha;                        ///< Current window opacity (0‑255) / 当前窗口透明度 (0‑255)
    int m_lang;                          ///< Current language (0=English, 1=Chinese) / 当前语言
    bool m_isDark;                       ///< Current theme (true=dark) / 当前主题 (true=深色)
    bool m_isServerRunning;               ///< Server running status / 服务器运行状态
    int m_storedModernOpacity = 210;      ///< Stored opacity value (persisted) / 存储的透明度值（持久化）
    bool m_storedIsRounded = true;        ///< Stored corner style / 存储的圆角样式
    bool m_isDebugMode = false;           ///< Debug (speed test) mode flag / 测速模式标志

    // UI component pointers / UI组件指针
    QPointer<QWidget> m_glossaryDrawer;   ///< Pointer to the glossary drawer (if open) / 术语表抽屉指针（如果打开）
    QSlider *m_opacitySlider;              ///< Opacity control slider / 透明度控制滑块
    QPushButton *btnClose, *btnMin;        ///< Window control buttons / 窗口控制按钮
    QPushButton *btnDebug, *btnLoad, *btnSave, *btnLang, *btnTheme, *btnExport, *btnBack; ///< Function buttons / 功能按钮

    SideGlassCombo *apiAddressCombo, *modelCombo, *glossaryCombo; ///< Custom combo boxes / 自定义组合框
    QLineEdit *apiKeyEdit, *portEdit, *prePromptEdit;             ///< Line edits / 行编辑
    QSpinBox *threadSpin, *contextSpin;                            ///< Spin boxes for integers / 整数微调框
    QDoubleSpinBox *tempSpin;                                      ///< Double spin box for temperature / 温度双精度微调框
    QTextEdit *systemPromptEdit, *logArea;                         ///< Text edit areas / 文本编辑区
    QCheckBox *chkGlossary, *chkLockGlossary, *chkLockSysPrompt, *chkBatch; ///< Check boxes / 复选框
    QPushButton *btnPower, *btnFetch, *btnTest, *btnClearCtx, *btnEditAuto, *btnEditGlossary, *btnSelectGlossary, *btnStop; ///< Buttons / 按钮
    QLabel *lblTokens, *lblApi, *lblKey, *lblMod, *lblPrt, *lblThd, *lblTmp, *lblCtx, *lblSys, *lblPre, *lblGlo; ///< Labels / 标签
};